//! Worldgen: a small solar system of SDF-driven planets.
//!
//! The root of the tree is the "space layer": a 3³ arrangement of
//! mostly-empty slots with a handful of planets placed at chosen
//! positions in world space [0, 3). Each planet's interior is
//! generated by recursively sampling its SDF — uniform-solid cells
//! deep inside, uniform-empty cells well above the surface, and
//! recursive descent only in the thin displaced-surface shell. Every
//! identical subtree is dedup'd by the content-addressed library, so
//! a planet's huge interior costs only O(depth) unique nodes.
//!
//! The `planets` vec on WorldState stores each planet's world-space
//! center / radius / gravity for runtime collision and camera
//! reorientation — the SDF is NOT re-sampled at runtime; the tree is
//! the cached snapshot.

use super::palette::block;
use super::sdf::{Planet, Vec3};
use super::state::WorldState;
use super::tree::*;

const TARGET_DEPTH: usize = 21;

/// Maximum SDF recursion levels below the root. Cells that straddle
/// the planet's surface are subdivided up to this depth to resolve
/// noise; below it we commit to solid-or-empty based on the center
/// sample and stop descending. Keeps generation bounded — the tree
/// is still TARGET_DEPTH deep overall (filler subtrees make up the
/// difference), but we don't uselessly subdivide the noise shell 21
/// levels deep.
const SDF_DETAIL_LEVELS: u32 = 5;

// Safety margin on SDF bounding checks; 0 = trust the SDF.
const SDF_SAFETY: f32 = 0.0;

pub fn generate_world() -> WorldState {
    let mut lib = NodeLibrary::default();

    // Planets placed in world-space [0, 3). Sizes are chosen so that
    // several fit comfortably with empty space in between (which the
    // player can fly through once outside any planet's influence).
    let planets = vec![
        Planet {
            center: [1.5, 1.5, 1.5],     // center of world
            radius: 0.45,
            noise_scale: 0.05,
            noise_freq: 40.0,
            noise_seed: 1337,
            gravity: 9.8,
            influence_radius: 0.9,
            surface_block: block::GRASS,
            core_block: block::STONE,
        },
        Planet {
            center: [0.5, 1.5, 0.7],
            radius: 0.22,
            noise_scale: 0.02,
            noise_freq: 90.0,
            noise_seed: 7,
            gravity: 6.0,
            influence_radius: 0.45,
            surface_block: block::SAND,
            core_block: block::STONE,
        },
        Planet {
            center: [2.4, 1.2, 2.3],
            radius: 0.30,
            noise_scale: 0.07,
            noise_freq: 30.0,
            noise_seed: 99,
            gravity: 12.0,
            influence_radius: 0.65,
            surface_block: block::DIRT,
            core_block: block::STONE,
        },
    ];

    // Precompute uniform-solid and uniform-empty fillers for each
    // subtree depth. fillers_solid[d] = a node whose entire subtree
    // of depth `d` is Stone; fillers_empty[d] = all Empty.
    let max_sub_depth = TARGET_DEPTH as u32;
    let mut solid_fillers: Vec<NodeId> = Vec::with_capacity(max_sub_depth as usize + 1);
    let mut empty_fillers: Vec<NodeId> = Vec::with_capacity(max_sub_depth as usize + 1);
    // depth 0 fillers are terminals — represented by inserting a
    // node whose 27 children are all terminal blocks / empties.
    let stone_leaf = lib.insert(uniform_children(Child::Block(block::STONE)));
    let empty_leaf = lib.insert(empty_children());
    solid_fillers.push(stone_leaf);
    empty_fillers.push(empty_leaf);
    for _ in 1..=max_sub_depth {
        let s = *solid_fillers.last().unwrap();
        let e = *empty_fillers.last().unwrap();
        solid_fillers.push(lib.insert(uniform_children(Child::Node(s))));
        empty_fillers.push(lib.insert(uniform_children(Child::Node(e))));
    }

    // Build the root (space layer) by recursively sampling all
    // planets into a single subtree of depth TARGET_DEPTH.
    let mut root_children = empty_children();
    let root_scale = 1.0f32; // each root child is 1 world unit wide
    for z in 0..3 {
        for y in 0..3 {
            for x in 0..3 {
                let origin = [x as f32, y as f32, z as f32];
                let child = build_space_subtree(
                    &mut lib, &planets, origin, root_scale,
                    TARGET_DEPTH as u32 - 1,
                    SDF_DETAIL_LEVELS,
                    &solid_fillers, &empty_fillers,
                );
                root_children[slot_index(x, y, z)] = child;
            }
        }
    }
    let root = lib.insert(root_children);
    lib.ref_inc(root);

    let world = WorldState { root, library: lib, planets };
    let d = world.tree_depth();
    eprintln!(
        "Generated solar system: {} planets, {} unique nodes, depth {}",
        world.planets.len(), world.library.len(), d,
    );
    world
}

/// Build a subtree for the cube [origin, origin + scale)^3 of the
/// space layer, containing the union of all planet SDFs. `depth` is
/// how many more levels of subdivision are available below this
/// node. At `depth == 0` we return a terminal (block or empty).
fn build_space_subtree(
    lib: &mut NodeLibrary,
    planets: &[Planet],
    origin: Vec3,
    scale: f32,
    depth: u32,
    sdf_budget: u32,
    solid: &[NodeId],
    empty: &[NodeId],
) -> Child {
    let half = scale * 0.5;
    let center = [origin[0] + half, origin[1] + half, origin[2] + half];
    let half_diag = scale * 0.8660254; // sqrt(3)/2

    // Nearest planet's SDF for this cell.
    let mut min_sdf = f32::INFINITY;
    for p in planets {
        let d = p.distance(center);
        if d < min_sdf { min_sdf = d; }
    }

    // Cell safely outside every planet: emit an empty filler.
    if min_sdf - half_diag - SDF_SAFETY > 0.0 {
        if depth == 0 { return Child::Empty; }
        return Child::Node(empty[(depth - 1) as usize]);
    }

    // Cell safely inside a planet: emit a solid filler.
    if min_sdf + half_diag + SDF_SAFETY < 0.0 {
        if depth == 0 { return Child::Block(block::STONE); }
        return Child::Node(solid[(depth - 1) as usize]);
    }

    // Leaf or SDF-budget exhausted: decide by center sample.
    if depth == 0 || sdf_budget == 0 {
        let is_solid = min_sdf < 0.0;
        if depth == 0 {
            return if is_solid { Child::Block(block::STONE) } else { Child::Empty };
        }
        return Child::Node(if is_solid {
            solid[(depth - 1) as usize]
        } else {
            empty[(depth - 1) as usize]
        });
    }

    // Near-surface interior cell: subdivide further.
    let child_scale = scale / 3.0;
    let mut children = empty_children();
    for z in 0..3 {
        for y in 0..3 {
            for x in 0..3 {
                let co = [
                    origin[0] + x as f32 * child_scale,
                    origin[1] + y as f32 * child_scale,
                    origin[2] + z as f32 * child_scale,
                ];
                children[slot_index(x, y, z)] = build_space_subtree(
                    lib, planets, co, child_scale, depth - 1, sdf_budget - 1,
                    solid, empty,
                );
            }
        }
    }
    Child::Node(lib.insert(children))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::world::edit;

    #[test]
    fn world_has_planets() {
        let w = generate_world();
        assert!(!w.planets.is_empty());
    }

    #[test]
    fn planet_center_is_solid() {
        let w = generate_world();
        let depth = w.tree_depth();
        // Interior of the main planet.
        let c = w.planets[0].center;
        assert!(edit::is_solid_at(&w.library, w.root, c, depth),
            "planet center should be solid");
    }

    #[test]
    fn deep_space_is_empty() {
        let w = generate_world();
        let depth = w.tree_depth();
        // A slot far from any planet (corner of world).
        assert!(!edit::is_solid_at(&w.library, w.root, [0.05, 2.9, 2.9], depth),
            "deep space should be empty");
    }

    #[test]
    fn dominant_planet_near_first() {
        let w = generate_world();
        let c = w.planets[0].center;
        let near = [c[0] + 0.05, c[1], c[2]];
        let p = w.dominant_planet(near).expect("should be inside first planet");
        assert_eq!(p.center, w.planets[0].center);
    }

    #[test]
    fn dominant_planet_none_in_void() {
        let w = generate_world();
        // Pick a spot far from any known planet.
        assert!(w.dominant_planet([0.02, 0.02, 0.02]).is_none());
    }
}
