//! Face-seam rotation table for the unified cubed-sphere DDA.
//!
//! When a ray exits a face subtree through one of the four UV edges,
//! it enters a neighbor face's subtree. Moving between faces requires
//! a single 3×3 rotation of `rd_local` (and the residual): the
//! current face's `(u, v, n)` basis rotates into the neighbor face's
//! `(u, v, n)` basis, preserving the shared-edge direction.
//!
//! Both the `(current_face, exit_edge) → (neighbor_face, rotation)`
//! mapping and the rotation matrices themselves are precomputed at
//! compile time here in [`SEAM_TABLE`]. The runtime helper
//! [`seam_rotation`] builds the table from scratch and exists solely
//! as a test-time cross-check — the shader will read [`SEAM_TABLE`]
//! straight out of a uniform.
//!
//! Exit-edge encoding: `0 = -u`, `1 = +u`, `2 = -v`, `3 = +v`.

use super::Face;

/// Neighbor-face + rotation describing one of the 24 (face, edge)
/// seam transitions.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct SeamTransition {
    /// Face the ray enters after crossing this edge.
    pub neighbor_face: Face,
    /// 3×3 rotation that maps a vector in `current_face`'s `(u, v, n)`
    /// basis into `neighbor_face`'s `(u, v, n)` basis.
    ///
    /// Equal to `R_neighbor · R_current^T`, where `R_face` has the
    /// face's `(u_axis, v_axis, n_axis)` as its rows (so `R_face ·
    /// body_vec = face_vec`).
    pub rotation: [[f32; 3]; 3],
}

/// The 24 seam transitions, indexed by
/// `SEAM_TABLE[current_face as usize][exit_edge]` where
/// `exit_edge ∈ 0..4`: `0 = -u, 1 = +u, 2 = -v, 3 = +v`.
///
/// Generated by running [`seam_rotation`] at authoring time;
/// kept as a `const` so neither the CPU nor the shader pays any
/// runtime cost to look up a transition.
pub const SEAM_TABLE: [[SeamTransition; 4]; 6] = [
    // PosX  (u = body -Z, v = body +Y, n = body +X)
    [
        // -u → body +Z → neighbor PosZ
        SeamTransition {
            neighbor_face: Face::PosZ,
            rotation: [
                [0.0, 0.0, 1.0],
                [0.0, 1.0, 0.0],
                [-1.0, 0.0, 0.0],
            ],
        },
        // +u → body -Z → neighbor NegZ
        SeamTransition {
            neighbor_face: Face::NegZ,
            rotation: [
                [0.0, 0.0, -1.0],
                [0.0, 1.0, 0.0],
                [1.0, 0.0, 0.0],
            ],
        },
        // -v → body -Y → neighbor NegY
        SeamTransition {
            neighbor_face: Face::NegY,
            rotation: [
                [0.0, 0.0, 1.0],
                [-1.0, 0.0, 0.0],
                [0.0, -1.0, 0.0],
            ],
        },
        // +v → body +Y → neighbor PosY
        SeamTransition {
            neighbor_face: Face::PosY,
            rotation: [
                [0.0, 0.0, 1.0],
                [1.0, 0.0, 0.0],
                [0.0, 1.0, 0.0],
            ],
        },
    ],
    // NegX  (u = body +Z, v = body +Y, n = body -X)
    [
        // -u → body -Z → NegZ
        SeamTransition {
            neighbor_face: Face::NegZ,
            rotation: [
                [0.0, 0.0, 1.0],
                [0.0, 1.0, 0.0],
                [-1.0, 0.0, 0.0],
            ],
        },
        // +u → body +Z → PosZ
        SeamTransition {
            neighbor_face: Face::PosZ,
            rotation: [
                [0.0, 0.0, -1.0],
                [0.0, 1.0, 0.0],
                [1.0, 0.0, 0.0],
            ],
        },
        // -v → body -Y → NegY
        SeamTransition {
            neighbor_face: Face::NegY,
            rotation: [
                [0.0, 0.0, -1.0],
                [1.0, 0.0, 0.0],
                [0.0, -1.0, 0.0],
            ],
        },
        // +v → body +Y → PosY
        SeamTransition {
            neighbor_face: Face::PosY,
            rotation: [
                [0.0, 0.0, -1.0],
                [-1.0, 0.0, 0.0],
                [0.0, 1.0, 0.0],
            ],
        },
    ],
    // PosY  (u = body +X, v = body -Z, n = body +Y)
    [
        // -u → body -X → NegX
        SeamTransition {
            neighbor_face: Face::NegX,
            rotation: [
                [0.0, -1.0, 0.0],
                [0.0, 0.0, 1.0],
                [-1.0, 0.0, 0.0],
            ],
        },
        // +u → body +X → PosX
        SeamTransition {
            neighbor_face: Face::PosX,
            rotation: [
                [0.0, 1.0, 0.0],
                [0.0, 0.0, 1.0],
                [1.0, 0.0, 0.0],
            ],
        },
        // -v → body +Z → PosZ
        SeamTransition {
            neighbor_face: Face::PosZ,
            rotation: [
                [1.0, 0.0, 0.0],
                [0.0, 0.0, 1.0],
                [0.0, -1.0, 0.0],
            ],
        },
        // +v → body -Z → NegZ
        SeamTransition {
            neighbor_face: Face::NegZ,
            rotation: [
                [-1.0, 0.0, 0.0],
                [0.0, 0.0, 1.0],
                [0.0, 1.0, 0.0],
            ],
        },
    ],
    // NegY  (u = body +X, v = body +Z, n = body -Y)
    [
        // -u → body -X → NegX
        SeamTransition {
            neighbor_face: Face::NegX,
            rotation: [
                [0.0, 1.0, 0.0],
                [0.0, 0.0, -1.0],
                [-1.0, 0.0, 0.0],
            ],
        },
        // +u → body +X → PosX
        SeamTransition {
            neighbor_face: Face::PosX,
            rotation: [
                [0.0, -1.0, 0.0],
                [0.0, 0.0, -1.0],
                [1.0, 0.0, 0.0],
            ],
        },
        // -v → body -Z → NegZ
        SeamTransition {
            neighbor_face: Face::NegZ,
            rotation: [
                [-1.0, 0.0, 0.0],
                [0.0, 0.0, -1.0],
                [0.0, -1.0, 0.0],
            ],
        },
        // +v → body +Z → PosZ
        SeamTransition {
            neighbor_face: Face::PosZ,
            rotation: [
                [1.0, 0.0, 0.0],
                [0.0, 0.0, -1.0],
                [0.0, 1.0, 0.0],
            ],
        },
    ],
    // PosZ  (u = body +X, v = body +Y, n = body +Z)
    [
        // -u → body -X → NegX
        SeamTransition {
            neighbor_face: Face::NegX,
            rotation: [
                [0.0, 0.0, 1.0],
                [0.0, 1.0, 0.0],
                [-1.0, 0.0, 0.0],
            ],
        },
        // +u → body +X → PosX
        SeamTransition {
            neighbor_face: Face::PosX,
            rotation: [
                [0.0, 0.0, -1.0],
                [0.0, 1.0, 0.0],
                [1.0, 0.0, 0.0],
            ],
        },
        // -v → body -Y → NegY
        SeamTransition {
            neighbor_face: Face::NegY,
            rotation: [
                [1.0, 0.0, 0.0],
                [0.0, 0.0, 1.0],
                [0.0, -1.0, 0.0],
            ],
        },
        // +v → body +Y → PosY
        SeamTransition {
            neighbor_face: Face::PosY,
            rotation: [
                [1.0, 0.0, 0.0],
                [0.0, 0.0, -1.0],
                [0.0, 1.0, 0.0],
            ],
        },
    ],
    // NegZ  (u = body -X, v = body +Y, n = body -Z)
    [
        // -u → body +X → PosX
        SeamTransition {
            neighbor_face: Face::PosX,
            rotation: [
                [0.0, 0.0, 1.0],
                [0.0, 1.0, 0.0],
                [-1.0, 0.0, 0.0],
            ],
        },
        // +u → body -X → NegX
        SeamTransition {
            neighbor_face: Face::NegX,
            rotation: [
                [0.0, 0.0, -1.0],
                [0.0, 1.0, 0.0],
                [1.0, 0.0, 0.0],
            ],
        },
        // -v → body -Y → NegY
        SeamTransition {
            neighbor_face: Face::NegY,
            rotation: [
                [-1.0, 0.0, 0.0],
                [0.0, 0.0, -1.0],
                [0.0, -1.0, 0.0],
            ],
        },
        // +v → body +Y → PosY
        SeamTransition {
            neighbor_face: Face::PosY,
            rotation: [
                [-1.0, 0.0, 0.0],
                [0.0, 0.0, 1.0],
                [0.0, 1.0, 0.0],
            ],
        },
    ],
];

// ─────────────────────────────────────────── runtime cross-check

/// Derive the `(neighbor_face, rotation)` pair for a given
/// `(current_face, exit_edge)` purely from the face-basis vectors.
///
/// This is the reference implementation that [`SEAM_TABLE`]'s
/// hard-coded entries are verified against — call it from tests and
/// debug tools; prefer [`SEAM_TABLE`] in hot code paths.
pub fn seam_rotation(current: Face, exit_edge: u8) -> (Face, [[f32; 3]; 3]) {
    let (u_cur, v_cur) = current.tangents();
    let n_cur = current.normal();
    // body-space direction the ray is heading in as it crosses the edge
    let body_dir: [f64; 3] = match exit_edge {
        0 => [-u_cur[0] as f64, -u_cur[1] as f64, -u_cur[2] as f64],
        1 => [u_cur[0] as f64, u_cur[1] as f64, u_cur[2] as f64],
        2 => [-v_cur[0] as f64, -v_cur[1] as f64, -v_cur[2] as f64],
        3 => [v_cur[0] as f64, v_cur[1] as f64, v_cur[2] as f64],
        _ => panic!("invalid exit edge {exit_edge}"),
    };
    // Neighbor face is the one whose normal points in body_dir.
    let neighbor = Face::ALL
        .iter()
        .copied()
        .find(|f| {
            let n = f.normal();
            (n[0] as f64 - body_dir[0]).abs() < 1.0e-6
                && (n[1] as f64 - body_dir[1]).abs() < 1.0e-6
                && (n[2] as f64 - body_dir[2]).abs() < 1.0e-6
        })
        .expect("every unit body-axis must be a face normal");

    // R_seam = R_neighbor · R_current^T.
    // Using rows u_cur, v_cur, n_cur for R_current, so R_current^T's
    // columns are those same rows.
    let r_cur = [
        [u_cur[0] as f64, u_cur[1] as f64, u_cur[2] as f64],
        [v_cur[0] as f64, v_cur[1] as f64, v_cur[2] as f64],
        [n_cur[0] as f64, n_cur[1] as f64, n_cur[2] as f64],
    ];
    let (u_nbr, v_nbr) = neighbor.tangents();
    let n_nbr = neighbor.normal();
    let r_nbr = [
        [u_nbr[0] as f64, u_nbr[1] as f64, u_nbr[2] as f64],
        [v_nbr[0] as f64, v_nbr[1] as f64, v_nbr[2] as f64],
        [n_nbr[0] as f64, n_nbr[1] as f64, n_nbr[2] as f64],
    ];

    // R_cur_T [i][j] = R_cur [j][i]
    let mut r_seam = [[0.0f64; 3]; 3];
    for i in 0..3 {
        for j in 0..3 {
            // (R_nbr · R_cur^T)[i][j] = Σ_k R_nbr[i][k] · R_cur[j][k]
            let mut sum = 0.0;
            for k in 0..3 {
                sum += r_nbr[i][k] * r_cur[j][k];
            }
            r_seam[i][j] = sum;
        }
    }

    let mut out = [[0.0f32; 3]; 3];
    for i in 0..3 {
        for j in 0..3 {
            out[i][j] = r_seam[i][j] as f32;
        }
    }

    (neighbor, out)
}

/// Given a forward seam crossing `(current, exit_edge)` that enters
/// `neighbor_face`, return the edge of `neighbor_face` whose outward
/// body direction points back at `current` — i.e. the edge a ray
/// would exit through if it reversed course and crossed the same
/// cube edge in the opposite direction. Used by the round-trip test.
pub fn reverse_edge(current: Face, exit_edge: u8) -> u8 {
    let (u_cur, v_cur) = current.tangents();
    let body_dir: [f32; 3] = match exit_edge {
        0 => [-u_cur[0], -u_cur[1], -u_cur[2]],
        1 => [u_cur[0], u_cur[1], u_cur[2]],
        2 => [-v_cur[0], -v_cur[1], -v_cur[2]],
        3 => [v_cur[0], v_cur[1], v_cur[2]],
        _ => panic!("invalid exit edge {exit_edge}"),
    };
    // Find the neighbor face.
    let neighbor = Face::ALL
        .iter()
        .copied()
        .find(|f| {
            let n = f.normal();
            (n[0] - body_dir[0]).abs() < 1.0e-5
                && (n[1] - body_dir[1]).abs() < 1.0e-5
                && (n[2] - body_dir[2]).abs() < 1.0e-5
        })
        .expect("neighbor exists");
    // Two cube faces share a cube edge, not antiparallel normals.
    // The reverse seam from `neighbor` back to `current` exits along
    // the edge of `neighbor` whose body direction points toward
    // `current`'s center — i.e. equals `n_current`.
    let n_cur = current.normal();
    let ret_dir = n_cur;
    let (u_nbr, v_nbr) = neighbor.tangents();
    // Match ret_dir against the neighbor's four edge body directions.
    // Edge body dirs are: 0=-u_nbr, 1=+u_nbr, 2=-v_nbr, 3=+v_nbr.
    let close = |a: [f32; 3], b: [f32; 3]| {
        (a[0] - b[0]).abs() < 1.0e-5
            && (a[1] - b[1]).abs() < 1.0e-5
            && (a[2] - b[2]).abs() < 1.0e-5
    };
    if close([-u_nbr[0], -u_nbr[1], -u_nbr[2]], ret_dir) {
        0
    } else if close(u_nbr, ret_dir) {
        1
    } else if close([-v_nbr[0], -v_nbr[1], -v_nbr[2]], ret_dir) {
        2
    } else if close(v_nbr, ret_dir) {
        3
    } else {
        panic!(
            "reverse edge not found: current {current:?} exit_edge {exit_edge} \
             neighbor {neighbor:?} ret_dir {ret_dir:?}"
        )
    }
}

// ────────────────────────────────────────────────────────── tests

#[cfg(test)]
mod tests {
    use super::*;

    fn matmul(a: [[f32; 3]; 3], b: [[f32; 3]; 3]) -> [[f32; 3]; 3] {
        let mut out = [[0.0f32; 3]; 3];
        for i in 0..3 {
            for j in 0..3 {
                let mut sum = 0.0;
                for k in 0..3 {
                    sum += a[i][k] * b[k][j];
                }
                out[i][j] = sum;
            }
        }
        out
    }

    fn transpose(a: [[f32; 3]; 3]) -> [[f32; 3]; 3] {
        let mut out = [[0.0f32; 3]; 3];
        for i in 0..3 {
            for j in 0..3 {
                out[i][j] = a[j][i];
            }
        }
        out
    }

    fn approx_mat(a: [[f32; 3]; 3], b: [[f32; 3]; 3], eps: f32) -> bool {
        for i in 0..3 {
            for j in 0..3 {
                if (a[i][j] - b[i][j]).abs() > eps {
                    return false;
                }
            }
        }
        true
    }

    #[test]
    fn seam_table_matches_runtime_derivation() {
        for (fi, &f) in Face::ALL.iter().enumerate() {
            for edge in 0..4u8 {
                let (nbr, r) = seam_rotation(f, edge);
                let entry = SEAM_TABLE[fi][edge as usize];
                assert_eq!(
                    entry.neighbor_face, nbr,
                    "face {f:?} edge {edge}: SEAM_TABLE neighbor {:?} != derived {nbr:?}",
                    entry.neighbor_face
                );
                assert!(
                    approx_mat(entry.rotation, r, 1e-6),
                    "face {f:?} edge {edge}: SEAM_TABLE rotation {:?} != derived {r:?}",
                    entry.rotation
                );
            }
        }
    }

    #[test]
    fn seam_table_coverage() {
        // Every entry must point to a face different from its source.
        for (fi, &f) in Face::ALL.iter().enumerate() {
            for edge in 0..4 {
                let entry = SEAM_TABLE[fi][edge];
                assert_ne!(
                    entry.neighbor_face, f,
                    "face {f:?} edge {edge}: neighbor is self"
                );
            }
        }

        // Every face should be reachable from at least one other face
        // (sanity check — every cube face has 4 neighbors).
        for &f in &Face::ALL {
            let mut count = 0;
            for (si, &s) in Face::ALL.iter().enumerate() {
                if s == f {
                    continue;
                }
                for edge in 0..4 {
                    if SEAM_TABLE[si][edge].neighbor_face == f {
                        count += 1;
                    }
                }
            }
            assert_eq!(
                count, 4,
                "face {f:?} should be a neighbor 4 times, got {count}"
            );
        }
    }

    #[test]
    fn seam_rotation_is_orthonormal() {
        let eye = [
            [1.0f32, 0.0, 0.0],
            [0.0, 1.0, 0.0],
            [0.0, 0.0, 1.0],
        ];
        for (fi, &f) in Face::ALL.iter().enumerate() {
            for edge in 0..4 {
                let r = SEAM_TABLE[fi][edge].rotation;
                let rrt = matmul(r, transpose(r));
                assert!(
                    approx_mat(rrt, eye, 1e-5),
                    "face {f:?} edge {edge}: R·R^T = {rrt:?}"
                );
                // Determinant = +1 (proper rotation, not reflection).
                let det = r[0][0] * (r[1][1] * r[2][2] - r[1][2] * r[2][1])
                    - r[0][1] * (r[1][0] * r[2][2] - r[1][2] * r[2][0])
                    + r[0][2] * (r[1][0] * r[2][1] - r[1][1] * r[2][0]);
                assert!(
                    (det - 1.0).abs() < 1e-5,
                    "face {f:?} edge {edge}: det(R) = {det}"
                );
            }
        }
    }

    #[test]
    fn seam_roundtrip() {
        // Going forward across an edge then back across the reverse
        // edge should be identity.
        for (fi, &f) in Face::ALL.iter().enumerate() {
            for edge in 0..4u8 {
                let fwd = SEAM_TABLE[fi][edge as usize];
                let ret_edge = reverse_edge(f, edge);
                let back = SEAM_TABLE[fwd.neighbor_face as usize][ret_edge as usize];
                assert_eq!(
                    back.neighbor_face, f,
                    "face {f:?} edge {edge} → {:?} edge {ret_edge} → {:?} (expected {f:?})",
                    fwd.neighbor_face, back.neighbor_face
                );
                let composed = matmul(back.rotation, fwd.rotation);
                let eye = [
                    [1.0f32, 0.0, 0.0],
                    [0.0, 1.0, 0.0],
                    [0.0, 0.0, 1.0],
                ];
                assert!(
                    approx_mat(composed, eye, 1e-5),
                    "face {f:?} edge {edge} round-trip = {composed:?}"
                );
            }
        }
    }
}
