//! Voxel-based NPC system with overlay subtree rendering.
//!
//! NPCs are small voxel models composed of articulated body parts
//! (head, torso, arms, legs). Each part is stored as a leaf node in
//! the shared `NodeLibrary`, rendered via the same tree-walk mesh
//! cache as terrain. Animation is rigid-body keyframe interpolation.
//!
//! Blueprints can be loaded from JSON files generated by the offline
//! pipeline (`tools/build_npc_blueprint.py`), or built procedurally.
//!
//! Press `N` to spawn a voxel NPC near the player.

use std::collections::HashMap;
use std::f32::consts::{PI, TAU};

use bevy::prelude::*;

use crate::block::{BslMaterial, Palette, PaletteEntry};
use crate::camera::FpsCam;
use crate::player::Player;
use crate::world::collision;
use crate::world::render::{OverlayInstance, OverlayList, OverlayPart};
use crate::world::tree::{
    voxel_idx, NodeId, Voxel, EMPTY_VOXEL, NODE_VOXELS, NODE_VOXELS_PER_AXIS,
};
use crate::world::view::{bevy_from_position, cell_size_at_layer, position_from_bevy, WorldAnchor};
use crate::world::{CameraZoom, WorldPosition, WorldState};

// ================================================================ data

/// A single body part: a small voxel grid with a pivot point.
#[derive(Clone)]
pub struct VoxelPart {
    pub name: String,
    pub size: [u8; 3],
    pub voxels: Vec<Voxel>,
    /// Pivot point in voxel-local coords (rotation center).
    pub pivot: Vec3,
    /// Default offset from the NPC root (rest pose position).
    pub rest_offset: Vec3,
}

/// One keyframe: per-part position offset and rotation.
#[derive(Clone)]
pub struct NpcPose {
    /// Keyed by part name -> (position offset from rest, rotation).
    pub parts: HashMap<String, (Vec3, Quat)>,
}

/// A named animation clip.
#[derive(Clone)]
pub struct NpcAnimation {
    pub keyframes: Vec<NpcPose>,
    pub frame_duration: f32,
    pub looping: bool,
}

/// Shared blueprint for an NPC type (raw voxel data).
#[derive(Clone, Resource)]
pub struct NpcBlueprint {
    pub name: String,
    pub parts: Vec<VoxelPart>,
    pub animations: HashMap<String, NpcAnimation>,
}

// =========================================== tree bridge

/// A body part stored as a NodeId in the shared NodeLibrary.
#[derive(Clone)]
pub struct TreePart {
    pub name: String,
    pub node_id: NodeId,
    pub size: [u8; 3],
    pub pivot: Vec3,
    pub rest_offset: Vec3,
}

/// Blueprint with tree-backed parts for overlay rendering.
#[derive(Clone, Resource)]
pub struct TreeBlueprint {
    pub name: String,
    pub parts: Vec<TreePart>,
    pub animations: HashMap<String, NpcAnimation>,
}

/// Convert a VoxelPart into a 25x25x25 leaf node in the library.
fn part_to_leaf(part: &VoxelPart, world: &mut WorldState) -> NodeId {
    let sx = part.size[0] as usize;
    let sy = part.size[1] as usize;
    let sz = part.size[2] as usize;
    assert!(
        sx <= NODE_VOXELS_PER_AXIS && sy <= NODE_VOXELS_PER_AXIS && sz <= NODE_VOXELS_PER_AXIS,
        "NPC part '{}' exceeds 25x25x25: {}x{}x{}",
        part.name, sx, sy, sz
    );

    let mut grid = Box::new([EMPTY_VOXEL; NODE_VOXELS]);
    for z in 0..sz {
        for y in 0..sy {
            for x in 0..sx {
                let src_idx = (z * sy + y) * sx + x;
                let v = part.voxels[src_idx];
                if v != EMPTY_VOXEL {
                    grid[voxel_idx(x, y, z)] = v;
                }
            }
        }
    }
    world.library.insert_leaf(grid)
}

/// Convert an NpcBlueprint into a TreeBlueprint, inserting all part
/// leaves into the shared NodeLibrary.
fn blueprint_to_tree(blueprint: &NpcBlueprint, world: &mut WorldState) -> TreeBlueprint {
    let parts: Vec<TreePart> = blueprint
        .parts
        .iter()
        .map(|p| TreePart {
            name: p.name.clone(),
            node_id: part_to_leaf(p, world),
            size: p.size,
            pivot: p.pivot,
            rest_offset: p.rest_offset,
        })
        .collect();

    TreeBlueprint {
        name: blueprint.name.clone(),
        parts,
        animations: blueprint.animations.clone(),
    }
}

// ============================================== blueprint JSON loading

mod blueprint_json {
    use super::*;
    use serde::Deserialize;

    #[derive(Deserialize)]
    pub struct BlueprintFile {
        pub palette: HashMap<String, [u8; 4]>,
        pub parts: HashMap<String, PartDef>,
        pub animations: HashMap<String, AnimDef>,
    }

    #[derive(Deserialize)]
    pub struct PartDef {
        pub size: [u8; 3],
        pub pivot: [f32; 3],
        pub rest_offset: [f32; 3],
        pub voxels_b64: String,
    }

    #[derive(Deserialize)]
    pub struct AnimDef {
        pub duration: f32,
        pub looping: bool,
        pub keyframes: Vec<KeyframeDef>,
    }

    #[derive(Deserialize)]
    #[allow(dead_code)]
    pub struct KeyframeDef {
        pub time: f32,
        pub parts: HashMap<String, PartTransform>,
    }

    #[derive(Deserialize)]
    pub struct PartTransform {
        pub translation: Option<[f32; 3]>,
        pub rotation: Option<[f32; 4]>, // [x, y, z, w]
    }

    /// Load a blueprint from JSON bytes, registering palette colors.
    pub fn load_blueprint(
        name: &str,
        json_bytes: &[u8],
        palette: &mut Palette,
        mat_assets: &mut Assets<BslMaterial>,
    ) -> Result<NpcBlueprint, String> {
        let file: BlueprintFile =
            serde_json::from_slice(json_bytes).map_err(|e| format!("JSON parse error: {e}"))?;

        // Register palette colors and build a remap from .vox color index -> game voxel index
        let mut color_remap: HashMap<u8, u8> = HashMap::new();
        for (idx_str, rgba) in &file.palette {
            let vox_idx: u8 = idx_str.parse().map_err(|e| format!("bad palette key: {e}"))?;
            let [r, g, b, a] = *rgba;
            let game_voxel = palette.register(
                PaletteEntry {
                    name: format!("npc_{name}_{vox_idx}"),
                    color: if a == 255 {
                        Color::srgb(r as f32 / 255.0, g as f32 / 255.0, b as f32 / 255.0)
                    } else {
                        Color::srgba(
                            r as f32 / 255.0,
                            g as f32 / 255.0,
                            b as f32 / 255.0,
                            a as f32 / 255.0,
                        )
                    },
                    roughness: 0.9,
                    metallic: 0.0,
                    alpha_mode: if a < 255 {
                        AlphaMode::Blend
                    } else {
                        AlphaMode::Opaque
                    },
                },
                mat_assets,
            );
            color_remap.insert(vox_idx, game_voxel);
        }

        // Parse parts — sort keys for deterministic ordering
        let mut part_names: Vec<&String> = file.parts.keys().collect();
        part_names.sort();

        let mut parts = Vec::new();
        for part_name in part_names {
            let def = &file.parts[part_name];
            let raw_voxels = base64_decode(&def.voxels_b64)?;

            let voxels: Vec<Voxel> = raw_voxels
                .into_iter()
                .map(|v| {
                    if v == 0 {
                        EMPTY_VOXEL
                    } else {
                        *color_remap.get(&v).unwrap_or(&EMPTY_VOXEL)
                    }
                })
                .collect();

            let expected_len =
                def.size[0] as usize * def.size[1] as usize * def.size[2] as usize;
            if voxels.len() != expected_len {
                return Err(format!(
                    "Part '{part_name}': voxel count {} != expected {expected_len}",
                    voxels.len()
                ));
            }

            parts.push(VoxelPart {
                name: part_name.clone(),
                size: def.size,
                voxels,
                pivot: Vec3::from_array(def.pivot),
                rest_offset: Vec3::from_array(def.rest_offset),
            });
        }

        // Parse animations
        let mut animations = HashMap::new();
        for (anim_name, anim_def) in &file.animations {
            if anim_def.keyframes.is_empty() {
                continue;
            }

            let frame_duration = if anim_def.keyframes.len() > 1 {
                anim_def.duration / (anim_def.keyframes.len() - 1) as f32
            } else {
                anim_def.duration
            };

            let keyframes: Vec<NpcPose> = anim_def
                .keyframes
                .iter()
                .map(|kf| {
                    let mut pose_parts = HashMap::new();
                    for (part_name, pt) in &kf.parts {
                        let translation = pt
                            .translation
                            .map(Vec3::from_array)
                            .unwrap_or(Vec3::ZERO);
                        let rotation = pt
                            .rotation
                            .map(|r| Quat::from_xyzw(r[0], r[1], r[2], r[3]))
                            .unwrap_or(Quat::IDENTITY);
                        pose_parts.insert(part_name.clone(), (translation, rotation));
                    }
                    NpcPose {
                        parts: pose_parts,
                    }
                })
                .collect();

            animations.insert(
                anim_name.clone(),
                NpcAnimation {
                    keyframes,
                    frame_duration,
                    looping: anim_def.looping,
                },
            );
        }

        Ok(NpcBlueprint {
            name: name.to_string(),
            parts,
            animations,
        })
    }

    fn base64_decode(s: &str) -> Result<Vec<u8>, String> {
        let table: [u8; 128] = {
            let mut t = [255u8; 128];
            for (i, &c) in b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
                .iter()
                .enumerate()
            {
                t[c as usize] = i as u8;
            }
            t
        };
        let bytes = s.as_bytes();
        let mut out = Vec::with_capacity(bytes.len() * 3 / 4);
        let mut buf = 0u32;
        let mut bits = 0u32;
        for &b in bytes {
            if b == b'=' || b == b'\n' || b == b'\r' {
                continue;
            }
            let val = if (b as usize) < 128 {
                table[b as usize]
            } else {
                255
            };
            if val == 255 {
                return Err(format!("invalid base64 char: {}", b as char));
            }
            buf = (buf << 6) | val as u32;
            bits += 6;
            if bits >= 8 {
                bits -= 8;
                out.push((buf >> bits) as u8);
                buf &= (1 << bits) - 1;
            }
        }
        Ok(out)
    }
}

// ====================================================== components

#[derive(Component)]
pub struct Npc;

#[derive(Component)]
struct NpcVelocity(Vec3);

#[derive(Component)]
struct NpcAi {
    heading: f32,
    change_timer: Timer,
}

#[derive(Component)]
struct NpcAnimState {
    current_anim: String,
    time: f32,
}

/// Per-instance part overrides for edited NPCs. When a voxel on an
/// NPC is edited, the affected part gets a new NodeId stored here
/// (clone-on-write). Unedited parts fall back to the blueprint's NodeId.
#[derive(Component, Default)]
pub struct NpcPartOverrides {
    pub overrides: HashMap<usize, NodeId>,
}

/// Per-frame computed part transforms, written by `npc_animate`,
/// read by `collect_overlays`. Each entry is `(offset, rotation)`
/// indexed by part index.
#[derive(Component)]
pub struct NpcPartTransforms {
    pub transforms: Vec<(Vec3, Quat)>,
}

// ========================================================= constants

const NPC_WALK_SPEED_CELLS: f32 = 3.0;
const NPC_GRAVITY_CELLS: f32 = 20.0;

// ============================================================ plugin

pub struct NpcPlugin;

impl Plugin for NpcPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(
            Update,
            (
                try_load_blueprint,
                spawn_npc_on_keypress,
                npc_ai,
                npc_animate,
                npc_physics,
                npc_despawn_on_zoom,
                collect_overlays
                    .after(npc_animate)
                    .after(crate::player::derive_transforms),
            ),
        );
    }
}

// ======================================= blueprint loading

/// Marker that we've attempted to load blueprints.
#[derive(Resource, Default)]
struct BlueprintLoaded(bool);

fn try_load_blueprint(
    mut commands: Commands,
    loaded: Option<Res<BlueprintLoaded>>,
    existing: Option<Res<TreeBlueprint>>,
    mut palette: Option<ResMut<Palette>>,
    mut mat_assets: ResMut<Assets<BslMaterial>>,
    mut world: ResMut<WorldState>,
) {
    if existing.is_some() {
        return;
    }
    if loaded.is_some_and(|l| l.0) {
        return;
    }
    commands.insert_resource(BlueprintLoaded(true));

    // Try loading from file
    let blueprint_path = "assets/npcs/fox.blueprint.json";
    if let Ok(bytes) = std::fs::read(blueprint_path) {
        if let Some(palette) = palette.as_mut() {
            match blueprint_json::load_blueprint("fox", &bytes, palette, &mut mat_assets) {
                Ok(bp) => {
                    info!(
                        "Loaded NPC blueprint '{}': {} parts, {} animations",
                        bp.name,
                        bp.parts.len(),
                        bp.animations.len()
                    );
                    let tree_bp = blueprint_to_tree(&bp, &mut world);
                    info!(
                        "Built tree blueprint '{}': {} tree parts",
                        tree_bp.name,
                        tree_bp.parts.len()
                    );
                    commands.insert_resource(tree_bp);
                    return;
                }
                Err(e) => {
                    warn!("Failed to load NPC blueprint: {e}");
                }
            }
        }
    }

    // Fallback: procedural humanoid
    info!("Using fallback procedural humanoid blueprint");
    let bp = build_humanoid_blueprint();
    let tree_bp = blueprint_to_tree(&bp, &mut world);
    commands.insert_resource(tree_bp);
}

// ======================================== default humanoid blueprint

fn build_humanoid_blueprint() -> NpcBlueprint {
    let skin: Voxel = 8;
    let shirt: Voxel = 6;
    let pants: Voxel = 7;
    let hair: Voxel = 4;
    let shoe: Voxel = 1;

    let head = {
        let (sx, sy, sz) = (4u8, 4, 4);
        let mut v = vec![EMPTY_VOXEL; (sx as usize) * (sy as usize) * (sz as usize)];
        let idx =
            |x: usize, y: usize, z: usize| (z * sy as usize + y) * sx as usize + x;
        for z in 0..sz as usize {
            for y in 0..sy as usize {
                for x in 0..sx as usize {
                    v[idx(x, y, z)] = skin;
                }
            }
        }
        for z in 0..sz as usize {
            for x in 0..sx as usize {
                v[idx(x, 3, z)] = hair;
            }
        }
        VoxelPart {
            name: "head".into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot: Vec3::new(2.0, 0.0, 2.0),
            rest_offset: Vec3::new(0.0, 10.0, 0.0),
        }
    };

    let torso = {
        let (sx, sy, sz) = (4u8, 5, 3);
        let mut v = vec![EMPTY_VOXEL; (sx as usize) * (sy as usize) * (sz as usize)];
        let idx =
            |x: usize, y: usize, z: usize| (z * sy as usize + y) * sx as usize + x;
        for z in 0..sz as usize {
            for y in 0..sy as usize {
                for x in 0..sx as usize {
                    v[idx(x, y, z)] = shirt;
                }
            }
        }
        VoxelPart {
            name: "torso".into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot: Vec3::new(2.0, 2.5, 1.5),
            rest_offset: Vec3::new(0.0, 7.5, 0.0),
        }
    };

    let make_limb = |name: &str, top_voxel: Voxel, bot_voxel: Voxel, pivot: Vec3, offset: Vec3| {
        let (sx, sy, sz) = (2u8, 5, 2);
        let mut v = vec![EMPTY_VOXEL; (sx as usize) * (sy as usize) * (sz as usize)];
        let idx =
            |x: usize, y: usize, z: usize| (z * sy as usize + y) * sx as usize + x;
        for z in 0..sz as usize {
            for y in 0..sy as usize {
                for x in 0..sx as usize {
                    v[idx(x, y, z)] = if y >= 3 { top_voxel } else { bot_voxel };
                }
            }
        }
        VoxelPart {
            name: name.into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot,
            rest_offset: offset,
        }
    };

    let arm_l = make_limb("arm_l", skin, shirt, Vec3::new(1.0, 5.0, 1.0), Vec3::new(-3.0, 10.0, 0.0));
    let arm_r = make_limb("arm_r", skin, shirt, Vec3::new(1.0, 5.0, 1.0), Vec3::new(3.0, 10.0, 0.0));
    let leg_l = make_limb("leg_l", pants, shoe, Vec3::new(1.0, 5.0, 1.0), Vec3::new(-1.0, 5.0, 0.0));
    let leg_r = make_limb("leg_r", pants, shoe, Vec3::new(1.0, 5.0, 1.0), Vec3::new(1.0, 5.0, 0.0));

    let mut animations = HashMap::new();

    animations.insert(
        "idle".into(),
        NpcAnimation {
            keyframes: vec![
                NpcPose { parts: HashMap::new() },
                NpcPose {
                    parts: HashMap::from([(
                        "head".into(),
                        (Vec3::new(0.0, 0.15, 0.0), Quat::IDENTITY),
                    )]),
                },
            ],
            frame_duration: 0.8,
            looping: true,
        },
    );

    let swing = 0.45;
    animations.insert(
        "walk".into(),
        NpcAnimation {
            keyframes: vec![
                NpcPose {
                    parts: HashMap::from([
                        ("leg_l".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("leg_r".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("arm_l".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("arm_r".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                    ]),
                },
                NpcPose { parts: HashMap::new() },
                NpcPose {
                    parts: HashMap::from([
                        ("leg_l".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("leg_r".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("arm_l".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("arm_r".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                    ]),
                },
                NpcPose { parts: HashMap::new() },
            ],
            frame_duration: 0.2,
            looping: true,
        },
    );

    NpcBlueprint {
        name: "humanoid".into(),
        parts: vec![head, torso, arm_l, arm_r, leg_l, leg_r],
        animations,
    }
}

// =========================================================== spawning

fn spawn_npc_on_keypress(
    mut commands: Commands,
    keyboard: Res<ButtonInput<KeyCode>>,
    tree_bp: Option<Res<TreeBlueprint>>,
    player_q: Query<&WorldPosition, With<Player>>,
    anchor: Res<WorldAnchor>,
    zoom: Res<CameraZoom>,
    cam_q: Query<&FpsCam>,
) {
    if !keyboard.just_pressed(KeyCode::KeyN) {
        return;
    }

    let Some(tree_bp) = tree_bp else { return };
    let Ok(player_pos) = player_q.single() else { return;
    };

    let cell = cell_size_at_layer(zoom.layer);
    let forward = if let Ok(cam) = cam_q.single() {
        Vec3::new(-cam.yaw.sin(), 0.0, -cam.yaw.cos())
    } else {
        Vec3::NEG_Z
    };

    let player_bevy = bevy_from_position(&player_pos.0, &anchor);
    let npc_bevy = player_bevy + forward * 5.0 * cell + Vec3::Y * 1.0;
    let Some(npc_pos) = position_from_bevy(npc_bevy, &anchor) else {
        warn!("NPC spawn position outside world");
        return;
    };

    let spawn_bevy = bevy_from_position(&npc_pos, &anchor);
    let heading = rand_heading();

    // Initialize part transforms at rest pose.
    let rest_transforms: Vec<(Vec3, Quat)> = tree_bp
        .parts
        .iter()
        .map(|p| (p.rest_offset, Quat::IDENTITY))
        .collect();

    // The root entity carries position (via derive_transforms) and
    // rotation (via npc_ai). Scale is NOT stored here — it's a
    // rendering concern computed per-frame in collect_overlays from
    // the current zoom layer.
    commands.spawn((
        Npc,
        WorldPosition(npc_pos),
        NpcVelocity(Vec3::ZERO),
        NpcAi {
            heading,
            change_timer: Timer::from_seconds(2.0 + rand_f32() * 3.0, TimerMode::Once),
        },
        NpcAnimState {
            current_anim: "walk".into(),
            time: 0.0,
        },
        NpcPartTransforms {
            transforms: rest_transforms,
        },
        NpcPartOverrides::default(),
        Transform::from_translation(spawn_bevy)
            .with_rotation(Quat::from_rotation_y(heading + PI)),
        Visibility::Visible,
    ));

    info!(
        "Spawned voxel NPC '{}' at {spawn_bevy:?} (layer {})",
        tree_bp.name, zoom.layer
    );
}

// =========================================================== animation

fn npc_animate(
    time: Res<Time>,
    tree_bp: Option<Res<TreeBlueprint>>,
    mut npc_q: Query<(&mut NpcAnimState, &mut NpcPartTransforms), With<Npc>>,
) {
    let Some(tree_bp) = tree_bp else { return };
    let dt = time.delta_secs();

    for (mut anim_state, mut part_tf) in &mut npc_q {
        anim_state.time += dt;

        let Some(anim) = tree_bp.animations.get(&anim_state.current_anim) else {
            continue;
        };
        if anim.keyframes.is_empty() {
            continue;
        }

        let total_duration = anim.keyframes.len() as f32 * anim.frame_duration;
        let t = if anim.looping {
            anim_state.time % total_duration
        } else {
            anim_state.time.min(total_duration - 0.001)
        };

        let frame_f = t / anim.frame_duration;
        let frame_a = (frame_f as usize) % anim.keyframes.len();
        let frame_b = (frame_a + 1) % anim.keyframes.len();
        let blend = frame_f.fract();

        let pose_a = &anim.keyframes[frame_a];
        let pose_b = &anim.keyframes[frame_b];

        for (i, part) in tree_bp.parts.iter().enumerate() {
            if i >= part_tf.transforms.len() {
                break;
            }

            let (pos_a, rot_a) = pose_a
                .parts
                .get(&part.name)
                .cloned()
                .unwrap_or((Vec3::ZERO, Quat::IDENTITY));
            let (pos_b, rot_b) = pose_b
                .parts
                .get(&part.name)
                .cloned()
                .unwrap_or((Vec3::ZERO, Quat::IDENTITY));

            let pos = pos_a.lerp(pos_b, blend);
            let rot = rot_a.slerp(rot_b, blend);

            part_tf.transforms[i] = (part.rest_offset + pos, rot);
        }
    }
}

// ================================================================= AI

fn npc_ai(
    time: Res<Time>,
    mut q: Query<
        (&mut NpcAi, &mut NpcVelocity, &mut Transform, &mut NpcAnimState),
        With<Npc>,
    >,
) {
    for (mut ai, mut vel, mut tf, mut anim) in &mut q {
        ai.change_timer.tick(time.delta());

        if ai.change_timer.just_finished() {
            ai.heading = rand_heading();
            ai.change_timer = Timer::from_seconds(2.0 + rand_f32() * 3.0, TimerMode::Once);
        }

        let speed = NPC_WALK_SPEED_CELLS;
        vel.0.x = -ai.heading.sin() * speed;
        vel.0.z = -ai.heading.cos() * speed;
        tf.rotation = Quat::from_rotation_y(ai.heading + PI);
        anim.current_anim = "walk".into();
    }
}

// ============================================================= physics

fn npc_physics(
    time: Res<Time>,
    world: Res<WorldState>,
    zoom: Res<CameraZoom>,
    mut q: Query<(&mut WorldPosition, &mut NpcVelocity), With<Npc>>,
) {
    let dt = time.delta_secs();
    let cell = cell_size_at_layer(zoom.layer);

    for (mut wpos, mut vel) in &mut q {
        vel.0.y -= NPC_GRAVITY_CELLS * cell * dt;
        let h_delta = bevy::math::Vec2::new(vel.0.x * cell * dt, vel.0.z * cell * dt);
        collision::move_and_collide(&mut wpos.0, &mut vel.0, h_delta, dt, &world, zoom.layer);
    }
}

// ====================================================== zoom despawn

/// Despawn NPC entities entirely when 2+ layers out from leaf layer.
fn npc_despawn_on_zoom(
    mut commands: Commands,
    zoom: Res<CameraZoom>,
    q: Query<Entity, With<Npc>>,
) {
    if !zoom.is_changed() {
        return;
    }
    let layers_out = crate::world::tree::MAX_LAYER.saturating_sub(zoom.layer);
    if layers_out >= 2 {
        for entity in &q {
            commands.entity(entity).despawn();
        }
    }
}

// ============================================== overlay collection

/// Populate `OverlayList` each frame from visible NPCs. Scale is
/// constant (leaf-layer based) — the NPC keeps its real-world size
/// in Bevy space. When you zoom out, the visible world grows around
/// it, so the NPC naturally appears smaller. That's real zoom.
pub fn collect_overlays(
    tree_bp: Option<Res<TreeBlueprint>>,
    zoom: Res<CameraZoom>,
    anchor: Res<WorldAnchor>,
    npc_q: Query<
        (Entity, &WorldPosition, &Transform, &NpcPartTransforms, Option<&NpcPartOverrides>),
        With<Npc>,
    >,
    mut overlay_list: ResMut<OverlayList>,
) {
    overlay_list.entries.clear();

    let Some(tree_bp) = tree_bp else { return };

    // NPCs live at the leaf layer. Skip rendering when 2+ layers out.
    let layers_out = crate::world::tree::MAX_LAYER.saturating_sub(zoom.layer);
    if layers_out >= 2 {
        return;
    }

    // Leaf-layer scale: NPC is ~1.5 leaf voxels tall. This never
    // changes with zoom — the NPC has a fixed real-world size.
    let scale = tree_npc_scale(crate::world::tree::MAX_LAYER, &tree_bp);

    for (entity, world_pos, tf, part_tf, overrides) in &npc_q {
        let bevy_pos = bevy_from_position(&world_pos.0, &anchor);

        let parts: Vec<OverlayPart> = tree_bp
            .parts
            .iter()
            .enumerate()
            .filter_map(|(i, tp)| {
                let (offset, rotation) = part_tf.transforms.get(i)?;
                let node_id = overrides
                    .and_then(|o| o.overrides.get(&i).copied())
                    .unwrap_or(tp.node_id);
                Some(OverlayPart {
                    node_id,
                    offset: *offset,
                    rotation: *rotation,
                    pivot: tp.pivot,
                })
            })
            .collect();

        overlay_list.entries.push(OverlayInstance {
            id: entity,
            parts,
            bevy_pos,
            rotation: tf.rotation,
            scale,
        });
    }
}

// ============================================== NPC voxel editing

/// Edit a single voxel on an NPC part. Clone-on-write: clones the
/// leaf voxel grid, patches one cell, inserts the new leaf, and
/// stores the new NodeId in the per-instance overrides.
pub fn edit_npc_voxel(
    world: &mut WorldState,
    overrides: &mut NpcPartOverrides,
    tree_bp: &TreeBlueprint,
    part_index: usize,
    local_voxel: [u8; 3],
    new_voxel: Voxel,
) {
    let base_id = overrides
        .overrides
        .get(&part_index)
        .copied()
        .unwrap_or(tree_bp.parts[part_index].node_id);

    let mut new_voxels = world
        .library
        .get(base_id)
        .expect("edit_npc_voxel: part node missing")
        .voxels
        .clone();
    new_voxels[voxel_idx(
        local_voxel[0] as usize,
        local_voxel[1] as usize,
        local_voxel[2] as usize,
    )] = new_voxel;
    let new_id = world.library.insert_leaf(new_voxels);
    overrides.overrides.insert(part_index, new_id);
}

// ============================================================= helpers

fn tree_npc_scale(view_layer: u8, tree_bp: &TreeBlueprint) -> f32 {
    let max_y: f32 = tree_bp
        .parts
        .iter()
        .map(|p| p.rest_offset.y + p.size[1] as f32)
        .fold(0.0f32, f32::max);
    let height = max_y.max(1.0);
    let cell = cell_size_at_layer(view_layer);
    (1.5 * cell) / height
}

fn rand_f32() -> f32 {
    let t = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .subsec_nanos();
    (t % 10000) as f32 / 10000.0
}

fn rand_heading() -> f32 {
    rand_f32() * TAU
}
