//! Voxel-based NPC system with overlay subtree rendering.
//!
//! NPCs are small voxel models composed of articulated body parts
//! (head, torso, arms, legs). Each part is stored as a leaf node in
//! the shared `NodeLibrary`, rendered via the same tree-walk mesh
//! cache as terrain. Animation is rigid-body keyframe interpolation.
//!
//! Blueprints can be loaded from JSON files generated by the offline
//! pipeline (`tools/build_npc_blueprint.py`), or built procedurally.
//!
//! Press `N` to spawn a voxel NPC near the player.

use std::collections::HashMap;
use std::f32::consts::{PI, TAU};

use bevy::prelude::*;

#[cfg(target_arch = "wasm32")]
use js_sys;

use crate::block::{BslMaterial, Palette, PaletteEntry};
use crate::camera::FpsCam;
use crate::player::Player;
use crate::world::collision;
use crate::world::npc_compute::{GpuNpcState, NpcGpuData};
use crate::world::overlay::{OverlayInstance, OverlayList, OverlayPart};
use crate::world::tree::{
    voxel_idx, NodeId, Voxel, EMPTY_VOXEL, NODE_VOXELS, NODE_VOXELS_PER_AXIS,
};
use crate::world::position::Position;
use crate::world::view::{bevy_from_position, cell_size_at_layer, position_from_bevy, WorldAnchor};
use crate::world::{CameraZoom, WorldPosition, WorldState};

// ================================================================ data

/// A single body part: a small voxel grid with a pivot point.
#[derive(Clone)]
pub struct VoxelPart {
    pub name: String,
    pub size: [u8; 3],
    pub voxels: Vec<Voxel>,
    /// Pivot point in voxel-local coords (rotation center).
    pub pivot: Vec3,
    /// Default offset from the NPC root (rest pose position).
    pub rest_offset: Vec3,
}

/// One keyframe: per-part position offset and rotation.
#[derive(Clone)]
pub struct NpcPose {
    /// Keyed by part name -> (position offset from rest, rotation).
    pub parts: HashMap<String, (Vec3, Quat)>,
}

/// A named animation clip.
#[derive(Clone)]
pub struct NpcAnimation {
    pub keyframes: Vec<NpcPose>,
    pub frame_duration: f32,
    pub looping: bool,
}

/// Shared blueprint for an NPC type (raw voxel data).
#[derive(Clone, Resource)]
pub struct NpcBlueprint {
    pub name: String,
    pub parts: Vec<VoxelPart>,
    pub animations: HashMap<String, NpcAnimation>,
}

// =========================================== tree bridge

/// A body part stored as a NodeId in the shared NodeLibrary.
#[derive(Clone)]
pub struct TreePart {
    pub name: String,
    pub node_id: NodeId,
    pub size: [u8; 3],
    pub pivot: Vec3,
    pub rest_offset: Vec3,
}

/// Blueprint with tree-backed parts for overlay rendering.
#[derive(Clone, Resource)]
pub struct TreeBlueprint {
    pub name: String,
    pub parts: Vec<TreePart>,
    pub animations: HashMap<String, NpcAnimation>,
}

/// Multiple NPC blueprints for variety.
#[derive(Resource, Default)]
pub struct TreeBlueprints {
    pub blueprints: Vec<TreeBlueprint>,
}

/// Convert a VoxelPart into a 25x25x25 leaf node in the library.
fn part_to_leaf(part: &VoxelPart, world: &mut WorldState) -> NodeId {
    let sx = part.size[0] as usize;
    let sy = part.size[1] as usize;
    let sz = part.size[2] as usize;
    assert!(
        sx <= NODE_VOXELS_PER_AXIS && sy <= NODE_VOXELS_PER_AXIS && sz <= NODE_VOXELS_PER_AXIS,
        "NPC part '{}' exceeds 25x25x25: {}x{}x{}",
        part.name, sx, sy, sz
    );

    let mut grid = Box::new([EMPTY_VOXEL; NODE_VOXELS]);
    for z in 0..sz {
        for y in 0..sy {
            for x in 0..sx {
                let src_idx = (z * sy + y) * sx + x;
                let v = part.voxels[src_idx];
                if v != EMPTY_VOXEL {
                    grid[voxel_idx(x, y, z)] = v;
                }
            }
        }
    }
    world.library.insert_leaf(grid)
}

/// Convert an NpcBlueprint into a TreeBlueprint, inserting all part
/// leaves into the shared NodeLibrary.
fn blueprint_to_tree(blueprint: &NpcBlueprint, world: &mut WorldState) -> TreeBlueprint {
    let parts: Vec<TreePart> = blueprint
        .parts
        .iter()
        .map(|p| TreePart {
            name: p.name.clone(),
            node_id: part_to_leaf(p, world),
            size: p.size,
            pivot: p.pivot,
            rest_offset: p.rest_offset,
        })
        .collect();

    TreeBlueprint {
        name: blueprint.name.clone(),
        parts,
        animations: blueprint.animations.clone(),
    }
}

// ============================================== blueprint JSON loading

mod blueprint_json {
    use super::*;
    use serde::Deserialize;

    #[derive(Deserialize)]
    pub struct BlueprintFile {
        pub palette: HashMap<String, [u8; 4]>,
        pub parts: HashMap<String, PartDef>,
        pub animations: HashMap<String, AnimDef>,
    }

    #[derive(Deserialize)]
    pub struct PartDef {
        pub size: [u8; 3],
        pub pivot: [f32; 3],
        pub rest_offset: [f32; 3],
        pub voxels_b64: String,
    }

    #[derive(Deserialize)]
    pub struct AnimDef {
        pub duration: f32,
        pub looping: bool,
        pub keyframes: Vec<KeyframeDef>,
    }

    #[derive(Deserialize)]
    #[allow(dead_code)]
    pub struct KeyframeDef {
        pub time: f32,
        pub parts: HashMap<String, PartTransform>,
    }

    #[derive(Deserialize)]
    pub struct PartTransform {
        pub translation: Option<[f32; 3]>,
        pub rotation: Option<[f32; 4]>, // [x, y, z, w]
    }

    /// Load a blueprint from JSON bytes, registering palette colors.
    pub fn load_blueprint(
        name: &str,
        json_bytes: &[u8],
        palette: &mut Palette,
        mat_assets: &mut Assets<BslMaterial>,
    ) -> Result<NpcBlueprint, String> {
        let file: BlueprintFile =
            serde_json::from_slice(json_bytes).map_err(|e| format!("JSON parse error: {e}"))?;

        // Register palette colors and build a remap from .vox color index -> game voxel index
        let mut color_remap: HashMap<u8, u8> = HashMap::new();
        for (idx_str, rgba) in &file.palette {
            let vox_idx: u8 = idx_str.parse().map_err(|e| format!("bad palette key: {e}"))?;
            let [r, g, b, a] = *rgba;
            let game_voxel = palette.register(
                PaletteEntry {
                    name: format!("npc_{name}_{vox_idx}"),
                    color: if a == 255 {
                        Color::srgb(r as f32 / 255.0, g as f32 / 255.0, b as f32 / 255.0)
                    } else {
                        Color::srgba(
                            r as f32 / 255.0,
                            g as f32 / 255.0,
                            b as f32 / 255.0,
                            a as f32 / 255.0,
                        )
                    },
                    roughness: 0.9,
                    metallic: 0.0,
                    alpha_mode: if a < 255 {
                        AlphaMode::Blend
                    } else {
                        AlphaMode::Opaque
                    },
                },
                mat_assets,
            );
            color_remap.insert(vox_idx, game_voxel);
        }

        // Parse parts — sort keys for deterministic ordering
        let mut part_names: Vec<&String> = file.parts.keys().collect();
        part_names.sort();

        let mut parts = Vec::new();
        for part_name in part_names {
            let def = &file.parts[part_name];
            let raw_voxels = base64_decode(&def.voxels_b64)?;

            let voxels: Vec<Voxel> = raw_voxels
                .into_iter()
                .map(|v| {
                    if v == 0 {
                        EMPTY_VOXEL
                    } else {
                        *color_remap.get(&v).unwrap_or(&EMPTY_VOXEL)
                    }
                })
                .collect();

            let expected_len =
                def.size[0] as usize * def.size[1] as usize * def.size[2] as usize;
            if voxels.len() != expected_len {
                return Err(format!(
                    "Part '{part_name}': voxel count {} != expected {expected_len}",
                    voxels.len()
                ));
            }

            parts.push(VoxelPart {
                name: part_name.clone(),
                size: def.size,
                voxels,
                pivot: Vec3::from_array(def.pivot),
                rest_offset: Vec3::from_array(def.rest_offset),
            });
        }

        // Parse animations
        let mut animations = HashMap::new();
        for (anim_name, anim_def) in &file.animations {
            if anim_def.keyframes.is_empty() {
                continue;
            }

            let frame_duration = if anim_def.keyframes.len() > 1 {
                anim_def.duration / (anim_def.keyframes.len() - 1) as f32
            } else {
                anim_def.duration
            };

            let keyframes: Vec<NpcPose> = anim_def
                .keyframes
                .iter()
                .map(|kf| {
                    let mut pose_parts = HashMap::new();
                    for (part_name, pt) in &kf.parts {
                        let translation = pt
                            .translation
                            .map(Vec3::from_array)
                            .unwrap_or(Vec3::ZERO);
                        let rotation = pt
                            .rotation
                            .map(|r| Quat::from_xyzw(r[0], r[1], r[2], r[3]))
                            .unwrap_or(Quat::IDENTITY);
                        pose_parts.insert(part_name.clone(), (translation, rotation));
                    }
                    NpcPose {
                        parts: pose_parts,
                    }
                })
                .collect();

            animations.insert(
                anim_name.clone(),
                NpcAnimation {
                    keyframes,
                    frame_duration,
                    looping: anim_def.looping,
                },
            );
        }

        Ok(NpcBlueprint {
            name: name.to_string(),
            parts,
            animations,
        })
    }

    fn base64_decode(s: &str) -> Result<Vec<u8>, String> {
        let table: [u8; 128] = {
            let mut t = [255u8; 128];
            for (i, &c) in b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
                .iter()
                .enumerate()
            {
                t[c as usize] = i as u8;
            }
            t
        };
        let bytes = s.as_bytes();
        let mut out = Vec::with_capacity(bytes.len() * 3 / 4);
        let mut buf = 0u32;
        let mut bits = 0u32;
        for &b in bytes {
            if b == b'=' || b == b'\n' || b == b'\r' {
                continue;
            }
            let val = if (b as usize) < 128 {
                table[b as usize]
            } else {
                255
            };
            if val == 255 {
                return Err(format!("invalid base64 char: {}", b as char));
            }
            buf = (buf << 6) | val as u32;
            bits += 6;
            if bits >= 8 {
                bits -= 8;
                out.push((buf >> bits) as u8);
                buf &= (1 << bits) - 1;
            }
        }
        Ok(out)
    }
}

// ====================================================== flat buffer

/// Maximum number of body parts per NPC.
const MAX_PARTS: usize = 8;

/// Per-NPC state, stored in a flat buffer for cache-friendly iteration.
/// No ECS overhead — just a struct in a Vec.
pub struct NpcState {
    pub position: Position,
    pub velocity: Vec3,
    pub heading: f32,
    /// Raw countdown timer (no Timer overhead).
    pub ai_timer: f32,
    pub anim_time: f32,
    /// Computed part transforms (rest_offset + animation).
    pub part_transforms: [(Vec3, Quat); MAX_PARTS],
    pub num_parts: u8,
    /// Facing rotation (derived from heading).
    pub rotation: Quat,
    /// If Some, this NPC has an ECS entity for editor overrides.
    pub handle_entity: Option<Entity>,
    /// Index into TreeBlueprints for this NPC's type.
    pub blueprint_idx: u8,
    /// Whether this slot is alive.
    pub alive: bool,
}

impl NpcState {
    fn new(position: Position, heading: f32, num_parts: usize) -> Self {
        Self {
            position,
            velocity: Vec3::ZERO,
            heading,
            blueprint_idx: 0,
            ai_timer: 3.0, // Set by caller with seeded random
            anim_time: 0.0,
            part_transforms: [(Vec3::ZERO, Quat::IDENTITY); MAX_PARTS],
            num_parts: num_parts.min(MAX_PARTS) as u8,
            rotation: Quat::from_rotation_y(heading + PI),
            handle_entity: None,
            alive: true,
        }
    }
}

/// The flat buffer holding all NPC state. Systems iterate this directly.
#[derive(Resource, Default)]
pub struct NpcBuffer {
    pub npcs: Vec<NpcState>,
}

impl NpcBuffer {
    pub fn len(&self) -> usize {
        self.npcs.len()
    }
}

// ====================================================== components (minimal)

/// Marker component on lightweight ECS entities that index into NpcBuffer.
/// Only needed for NPCs that have been edited (NpcPartOverrides).
#[derive(Component)]
pub struct Npc;

/// Index into NpcBuffer, stored on the ECS entity for editor access.
#[derive(Component)]
pub struct NpcHandle(pub usize);

/// Per-instance part overrides for edited NPCs.
#[derive(Component, Default)]
pub struct NpcPartOverrides {
    pub overrides: HashMap<usize, NodeId>,
}

// ========================================================= constants

const NPC_WALK_SPEED_CELLS: f32 = 3.0;
const NPC_GRAVITY_CELLS: f32 = 20.0;
const MASS_SPAWN_COUNT: usize = 10_000;

/// Frame counter for staggering animation updates.
#[derive(Resource, Default)]
struct NpcFrameCounter(u32);

const NPC_UPDATE_STAGGER: u32 = 4;

// ============================================================ plugin

pub struct NpcPlugin;

impl Plugin for NpcPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<NpcFrameCounter>()
            .init_resource::<NpcBuffer>()
            .add_systems(
                Update,
                (
                    try_load_blueprint,
                    spawn_npc_on_keypress,
                    js_spawn_bridge,
                    npc_buf_ai,
                    npc_buf_animate,
                    npc_buf_physics,
                    manage_npc_handles,
                    npc_despawn_on_zoom,
                    sync_gpu_uniforms,
                    collect_overlays_from_buffer
                        .after(npc_buf_animate)
                        .after(crate::player::derive_transforms),
                ),
            );
    }
}

// ======================================= blueprint loading

/// Marker that we've attempted to load blueprints.
#[derive(Resource, Default)]
struct BlueprintLoaded(bool);

fn try_load_blueprint(
    mut commands: Commands,
    loaded: Option<Res<BlueprintLoaded>>,
    existing: Option<Res<TreeBlueprint>>,
    mut palette: Option<ResMut<Palette>>,
    mut mat_assets: ResMut<Assets<BslMaterial>>,
    mut world: ResMut<WorldState>,
) {
    if existing.is_some() {
        return;
    }
    if loaded.is_some_and(|l| l.0) {
        return;
    }
    commands.insert_resource(BlueprintLoaded(true));

    // Try loading from file (filesystem not available on WASM)
    #[cfg(not(target_arch = "wasm32"))]
    {
        let blueprint_path = "assets/npcs/fox.blueprint.json";
        if let Ok(bytes) = std::fs::read(blueprint_path) {
            if let Some(palette) = palette.as_mut() {
                match blueprint_json::load_blueprint("fox", &bytes, palette, &mut mat_assets) {
                    Ok(bp) => {
                        info!(
                            "Loaded NPC blueprint '{}': {} parts, {} animations",
                            bp.name,
                            bp.parts.len(),
                            bp.animations.len()
                        );
                        let tree_bp = blueprint_to_tree(&bp, &mut world);
                        info!(
                            "Built tree blueprint '{}': {} tree parts",
                            tree_bp.name,
                            tree_bp.parts.len()
                        );
                        commands.insert_resource(tree_bp);
                        return;
                    }
                    Err(e) => {
                        warn!("Failed to load NPC blueprint: {e}");
                    }
                }
            }
        }
    }

    // Build all procedural blueprints.
    let blueprints = vec![
        build_humanoid_blueprint(),
        build_critter_blueprint(),
        build_golem_blueprint(),
    ];

    let mut tree_blueprints = TreeBlueprints::default();
    for bp in &blueprints {
        info!("Built NPC blueprint '{}': {} parts", bp.name, bp.parts.len());
        tree_blueprints.blueprints.push(blueprint_to_tree(bp, &mut world));
    }

    // First blueprint is the default (for backward compat).
    if let Some(first) = tree_blueprints.blueprints.first() {
        commands.insert_resource(first.clone());
    }
    commands.insert_resource(tree_blueprints);
}

// ======================================== default humanoid blueprint

fn build_humanoid_blueprint() -> NpcBlueprint {
    let skin: Voxel = 8;
    let shirt: Voxel = 6;
    let pants: Voxel = 7;
    let hair: Voxel = 4;
    let shoe: Voxel = 1;

    let head = {
        let (sx, sy, sz) = (4u8, 4, 4);
        let mut v = vec![EMPTY_VOXEL; (sx as usize) * (sy as usize) * (sz as usize)];
        let idx =
            |x: usize, y: usize, z: usize| (z * sy as usize + y) * sx as usize + x;
        for z in 0..sz as usize {
            for y in 0..sy as usize {
                for x in 0..sx as usize {
                    v[idx(x, y, z)] = skin;
                }
            }
        }
        for z in 0..sz as usize {
            for x in 0..sx as usize {
                v[idx(x, 3, z)] = hair;
            }
        }
        VoxelPart {
            name: "head".into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot: Vec3::new(2.0, 0.0, 2.0),
            rest_offset: Vec3::new(0.0, 10.0, 0.0),
        }
    };

    let torso = {
        let (sx, sy, sz) = (4u8, 5, 3);
        let mut v = vec![EMPTY_VOXEL; (sx as usize) * (sy as usize) * (sz as usize)];
        let idx =
            |x: usize, y: usize, z: usize| (z * sy as usize + y) * sx as usize + x;
        for z in 0..sz as usize {
            for y in 0..sy as usize {
                for x in 0..sx as usize {
                    v[idx(x, y, z)] = shirt;
                }
            }
        }
        VoxelPart {
            name: "torso".into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot: Vec3::new(2.0, 2.5, 1.5),
            rest_offset: Vec3::new(0.0, 7.5, 0.0),
        }
    };

    let make_limb = |name: &str, top_voxel: Voxel, bot_voxel: Voxel, pivot: Vec3, offset: Vec3| {
        let (sx, sy, sz) = (2u8, 5, 2);
        let mut v = vec![EMPTY_VOXEL; (sx as usize) * (sy as usize) * (sz as usize)];
        let idx =
            |x: usize, y: usize, z: usize| (z * sy as usize + y) * sx as usize + x;
        for z in 0..sz as usize {
            for y in 0..sy as usize {
                for x in 0..sx as usize {
                    v[idx(x, y, z)] = if y >= 3 { top_voxel } else { bot_voxel };
                }
            }
        }
        VoxelPart {
            name: name.into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot,
            rest_offset: offset,
        }
    };

    let arm_l = make_limb("arm_l", skin, shirt, Vec3::new(1.0, 5.0, 1.0), Vec3::new(-3.0, 10.0, 0.0));
    let arm_r = make_limb("arm_r", skin, shirt, Vec3::new(1.0, 5.0, 1.0), Vec3::new(3.0, 10.0, 0.0));
    let leg_l = make_limb("leg_l", pants, shoe, Vec3::new(1.0, 5.0, 1.0), Vec3::new(-1.0, 5.0, 0.0));
    let leg_r = make_limb("leg_r", pants, shoe, Vec3::new(1.0, 5.0, 1.0), Vec3::new(1.0, 5.0, 0.0));

    let mut animations = HashMap::new();

    animations.insert(
        "idle".into(),
        NpcAnimation {
            keyframes: vec![
                NpcPose { parts: HashMap::new() },
                NpcPose {
                    parts: HashMap::from([(
                        "head".into(),
                        (Vec3::new(0.0, 0.15, 0.0), Quat::IDENTITY),
                    )]),
                },
            ],
            frame_duration: 0.8,
            looping: true,
        },
    );

    let swing = 0.45;
    animations.insert(
        "walk".into(),
        NpcAnimation {
            keyframes: vec![
                NpcPose {
                    parts: HashMap::from([
                        ("leg_l".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("leg_r".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("arm_l".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("arm_r".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                    ]),
                },
                NpcPose { parts: HashMap::new() },
                NpcPose {
                    parts: HashMap::from([
                        ("leg_l".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("leg_r".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("arm_l".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("arm_r".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                    ]),
                },
                NpcPose { parts: HashMap::new() },
            ],
            frame_duration: 0.2,
            looping: true,
        },
    );

    NpcBlueprint {
        name: "humanoid".into(),
        parts: vec![head, torso, arm_l, arm_r, leg_l, leg_r],
        animations,
    }
}

fn build_critter_blueprint() -> NpcBlueprint {
    let body: Voxel = 3; // wood brown
    let eye: Voxel = 1;  // stone grey

    let body_part = {
        let (sx, sy, sz) = (3u8, 2, 4);
        let mut v = vec![EMPTY_VOXEL; (sx as usize) * (sy as usize) * (sz as usize)];
        let idx = |x: usize, y: usize, z: usize| (z * sy as usize + y) * sx as usize + x;
        for z in 0..sz as usize {
            for y in 0..sy as usize {
                for x in 0..sx as usize {
                    v[idx(x, y, z)] = body;
                }
            }
        }
        // Eyes on front face
        v[idx(0, 1, 0)] = eye;
        v[idx(2, 1, 0)] = eye;
        VoxelPart {
            name: "body".into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot: Vec3::new(1.5, 1.0, 2.0),
            rest_offset: Vec3::new(-1.5, 2.0, -2.0),
        }
    };

    let make_leg = |name: &str, offset: Vec3| {
        let (sx, sy, sz) = (1u8, 2, 1);
        let mut v = vec![body; (sx as usize) * (sy as usize) * (sz as usize)];
        VoxelPart {
            name: name.into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot: Vec3::new(0.5, 2.0, 0.5),
            rest_offset: offset,
        }
    };

    let leg_fl = make_leg("leg_fl", Vec3::new(-1.5, 0.0, -2.0));
    let leg_fr = make_leg("leg_fr", Vec3::new(0.5, 0.0, -2.0));
    let leg_bl = make_leg("leg_bl", Vec3::new(-1.5, 0.0, 1.0));
    let leg_br = make_leg("leg_br", Vec3::new(0.5, 0.0, 1.0));

    let mut animations = HashMap::new();
    let swing = 0.35;
    animations.insert(
        "walk".into(),
        NpcAnimation {
            keyframes: vec![
                NpcPose {
                    parts: HashMap::from([
                        ("leg_fl".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("leg_br".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("leg_fr".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("leg_bl".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                    ]),
                },
                NpcPose { parts: HashMap::new() },
                NpcPose {
                    parts: HashMap::from([
                        ("leg_fl".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("leg_br".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("leg_fr".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("leg_bl".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                    ]),
                },
                NpcPose { parts: HashMap::new() },
            ],
            frame_duration: 0.15,
            looping: true,
        },
    );

    NpcBlueprint {
        name: "critter".into(),
        parts: vec![body_part, leg_fl, leg_fr, leg_bl, leg_br],
        animations,
    }
}

fn build_golem_blueprint() -> NpcBlueprint {
    let stone: Voxel = 1;  // stone grey
    let moss: Voxel = 5;   // leaf green
    let glow: Voxel = 7;   // blue

    let head = {
        let (sx, sy, sz) = (3u8, 3, 3);
        let mut v = vec![stone; (sx as usize) * (sy as usize) * (sz as usize)];
        let idx = |x: usize, y: usize, z: usize| (z * sy as usize + y) * sx as usize + x;
        v[idx(0, 2, 0)] = glow;
        v[idx(2, 2, 0)] = glow;
        VoxelPart {
            name: "head".into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot: Vec3::new(1.5, 0.0, 1.5),
            rest_offset: Vec3::new(-1.5, 15.0, -1.5),
        }
    };

    let torso = {
        let (sx, sy, sz) = (5u8, 7, 4);
        let mut v = vec![stone; (sx as usize) * (sy as usize) * (sz as usize)];
        let idx = |x: usize, y: usize, z: usize| (z * sy as usize + y) * sx as usize + x;
        // Moss on top
        for z in 0..sz as usize {
            for x in 0..sx as usize {
                v[idx(x, 6, z)] = moss;
            }
        }
        VoxelPart {
            name: "torso".into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot: Vec3::new(2.5, 3.5, 2.0),
            rest_offset: Vec3::new(-2.5, 8.0, -2.0),
        }
    };

    let make_limb = |name: &str, pivot: Vec3, offset: Vec3| {
        let (sx, sy, sz) = (2u8, 6, 2);
        let v = vec![stone; (sx as usize) * (sy as usize) * (sz as usize)];
        VoxelPart {
            name: name.into(),
            size: [sx, sy, sz],
            voxels: v,
            pivot,
            rest_offset: offset,
        }
    };

    let arm_l = make_limb("arm_l", Vec3::new(1.0, 6.0, 1.0), Vec3::new(-4.5, 9.0, -1.0));
    let arm_r = make_limb("arm_r", Vec3::new(1.0, 6.0, 1.0), Vec3::new(2.5, 9.0, -1.0));
    let leg_l = make_limb("leg_l", Vec3::new(1.0, 6.0, 1.0), Vec3::new(-2.5, 2.0, -1.0));
    let leg_r = make_limb("leg_r", Vec3::new(1.0, 6.0, 1.0), Vec3::new(0.5, 2.0, -1.0));

    let mut animations = HashMap::new();
    let swing = 0.25;
    animations.insert(
        "walk".into(),
        NpcAnimation {
            keyframes: vec![
                NpcPose {
                    parts: HashMap::from([
                        ("leg_l".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("leg_r".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("arm_l".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("arm_r".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                    ]),
                },
                NpcPose { parts: HashMap::new() },
                NpcPose {
                    parts: HashMap::from([
                        ("leg_l".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                        ("leg_r".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("arm_l".into(), (Vec3::ZERO, Quat::from_rotation_x(swing))),
                        ("arm_r".into(), (Vec3::ZERO, Quat::from_rotation_x(-swing))),
                    ]),
                },
                NpcPose { parts: HashMap::new() },
            ],
            frame_duration: 0.3,
            looping: true,
        },
    );

    NpcBlueprint {
        name: "golem".into(),
        parts: vec![head, torso, arm_l, arm_r, leg_l, leg_r],
        animations,
    }
}

// =========================================================== spawning

fn spawn_npc_on_keypress(
    keyboard: Res<ButtonInput<KeyCode>>,
    tree_bp: Option<Res<TreeBlueprint>>,
    blueprints: Option<Res<TreeBlueprints>>,
    player_q: Query<&WorldPosition, With<Player>>,
    mut npc_buffer: ResMut<NpcBuffer>,
    mut gpu_data: ResMut<NpcGpuData>,
    anchor: Res<WorldAnchor>,
    zoom: Res<CameraZoom>,
    cam_q: Query<&FpsCam>,
) {
    // N = spawn 1 NPC, M = mass spawn batch
    let count = if keyboard.just_pressed(KeyCode::KeyN) {
        1usize
    } else if keyboard.just_pressed(KeyCode::KeyM) {
        MASS_SPAWN_COUNT
    } else {
        return;
    };

    let Some(tree_bp) = tree_bp else { return };
    let Ok(player_pos) = player_q.single() else { return };

    let cell = cell_size_at_layer(zoom.layer);
    let forward = if let Ok(cam) = cam_q.single() {
        Vec3::new(-cam.yaw.sin(), 0.0, -cam.yaw.cos())
    } else {
        Vec3::NEG_Z
    };

    let player_bevy = bevy_from_position(&player_pos.0, &anchor);
    let num_parts = tree_bp.parts.len();
    let existing = npc_buffer.len();

    // Pre-compute rest pose transforms.
    let mut rest_parts = [(Vec3::ZERO, Quat::IDENTITY); MAX_PARTS];
    for (i, p) in tree_bp.parts.iter().enumerate().take(MAX_PARTS) {
        rest_parts[i] = (p.rest_offset, Quat::IDENTITY);
    }

    npc_buffer.npcs.reserve(count);

    for i in 0..count {
        let (offset_x, offset_z) = if count > 1 {
            let grid_side = (count as f32).sqrt().ceil() as usize;
            let row = i / grid_side;
            let col = i % grid_side;
            let spacing = 3.0 * cell;
            let half = (grid_side as f32) * spacing / 2.0;
            (col as f32 * spacing - half, row as f32 * spacing - half)
        } else {
            (0.0, 0.0)
        };

        let npc_bevy = player_bevy
            + forward * 5.0 * cell
            + Vec3::new(offset_x, 1.0, offset_z);
        let Some(npc_pos) = position_from_bevy(npc_bevy, &anchor) else {
            continue;
        };

        // Pick a random blueprint type for variety.
        let num_types = blueprints.as_ref().map(|b| b.blueprints.len()).unwrap_or(1);
        let bp_idx = if num_types > 1 {
            (rand_f32_seeded(i as u32 + 3333) * num_types as f32) as u8 % num_types as u8
        } else {
            0
        };
        let bp_parts = blueprints
            .as_ref()
            .and_then(|b| b.blueprints.get(bp_idx as usize))
            .map(|b| b.parts.len())
            .unwrap_or(num_parts);

        let heading = rand_heading_seeded(i as u32);
        let mut npc = NpcState::new(npc_pos, heading, bp_parts);
        npc.blueprint_idx = bp_idx;
        npc.anim_time = rand_f32_seeded(i as u32 + 5555) * 2.0;
        npc.ai_timer = 2.0 + rand_f32_seeded(i as u32 + 9999) * 3.0;

        // Set rest pose from the selected blueprint.
        if let Some(bps) = blueprints.as_ref() {
            if let Some(bp) = bps.blueprints.get(bp_idx as usize) {
                for (j, p) in bp.parts.iter().enumerate().take(MAX_PARTS) {
                    npc.part_transforms[j] = (p.rest_offset, Quat::IDENTITY);
                }
            }
        } else {
            npc.part_transforms = rest_parts;
        }

        npc_buffer.npcs.push(npc);
    }

    gpu_data.dirty = true;

    info!(
        "Spawned {} NPC(s) '{}' (total now ~{}, layer {})",
        count, tree_bp.name, existing + count, zoom.layer,
    );
}

// =========================================================== buffer systems

fn npc_buf_ai(
    time: Res<Time>,
    mut frame: ResMut<NpcFrameCounter>,
    mut npc_buffer: ResMut<NpcBuffer>,
) {
    let dt = time.delta_secs();
    let fc = frame.0;
    frame.0 = fc.wrapping_add(1);

    for (i, npc) in npc_buffer.npcs.iter_mut().enumerate() {
        if !npc.alive { continue; }

        // Stagger timer: only 1/N per frame.
        if (i as u32) % NPC_UPDATE_STAGGER == fc % NPC_UPDATE_STAGGER {
            npc.ai_timer -= dt * NPC_UPDATE_STAGGER as f32;
            if npc.ai_timer <= 0.0 {
                npc.heading = rand_f32_seeded(fc.wrapping_mul(1000).wrapping_add(i as u32)) * TAU;
                npc.ai_timer = 2.0 + rand_f32_seeded(fc.wrapping_add(i as u32 + 7777)) * 3.0;
            }
        }

        // Velocity and rotation: always update (cheap).
        let speed = NPC_WALK_SPEED_CELLS;
        npc.velocity.x = -npc.heading.sin() * speed;
        npc.velocity.z = -npc.heading.cos() * speed;
        npc.rotation = Quat::from_rotation_y(npc.heading + PI);
    }
}

fn npc_buf_animate(
    time: Res<Time>,
    frame: Res<NpcFrameCounter>,
    blueprints: Option<Res<TreeBlueprints>>,
    mut npc_buffer: ResMut<NpcBuffer>,
) {
    let Some(blueprints) = blueprints else { return };
    if blueprints.blueprints.is_empty() { return; }
    let dt = time.delta_secs();
    let fc = frame.0;

    for (i, npc) in npc_buffer.npcs.iter_mut().enumerate() {
        if !npc.alive { continue; }

        npc.anim_time += dt;

        if (i as u32) % NPC_UPDATE_STAGGER != fc % NPC_UPDATE_STAGGER {
            continue;
        }

        let bp = &blueprints.blueprints[npc.blueprint_idx as usize % blueprints.blueprints.len()];
        let Some(anim) = bp.animations.get("walk") else { continue };
        if anim.keyframes.is_empty() || anim.frame_duration <= 0.0 { continue; }
        let total_duration = anim.keyframes.len() as f32 * anim.frame_duration;
        if total_duration <= 0.0 { continue; }

        let t = if anim.looping {
            npc.anim_time % total_duration
        } else {
            npc.anim_time.min(total_duration - 0.001)
        };

        let frame_f = t / anim.frame_duration;
        let frame_a = (frame_f as usize) % anim.keyframes.len();
        let frame_b = (frame_a + 1) % anim.keyframes.len();
        let blend = frame_f.fract();

        let pose_a = &anim.keyframes[frame_a];
        let pose_b = &anim.keyframes[frame_b];

        for (j, part) in bp.parts.iter().enumerate().take(npc.num_parts as usize) {
            let (pos_a, rot_a) = pose_a
                .parts
                .get(&part.name)
                .cloned()
                .unwrap_or((Vec3::ZERO, Quat::IDENTITY));
            let (pos_b, rot_b) = pose_b
                .parts
                .get(&part.name)
                .cloned()
                .unwrap_or((Vec3::ZERO, Quat::IDENTITY));

            npc.part_transforms[j] = (
                part.rest_offset + pos_a.lerp(pos_b, blend),
                rot_a.slerp(rot_b, blend),
            );
        }
    }
}

/// Ground collision via spatial cache: O(1) lookups, lazy population.
///
/// Uses the **player's** anchor for the ground cache queries (the
/// cache stores absolute leaf Y internally, so the anchor only
/// affects the bevy-space conversion), but builds a **local anchor**
/// for each NPC's own position when folding the result back into
/// `Position` -- keeping f32 values tiny for NPCs far from the
/// player.
fn npc_buf_physics(
    time: Res<Time>,
    world: Res<WorldState>,
    zoom: Res<CameraZoom>,
    anchor: Res<WorldAnchor>,
    mut ground_cache: ResMut<crate::world::heightmap::GroundCache>,
    mut npc_buffer: ResMut<NpcBuffer>,
) {
    let dt = time.delta_secs();
    let cell = cell_size_at_layer(zoom.layer);

    for npc in &mut npc_buffer.npcs {
        if !npc.alive { continue; }

        // Use a local anchor at the NPC's own position so all f32
        // arithmetic stays small, regardless of distance from player.
        let npc_anchor = WorldAnchor {
            leaf_coord: crate::world::view::position_to_leaf_coord(&npc.position),
        };
        let bevy_pos = bevy_from_position(&npc.position, &npc_anchor);

        let new_x = bevy_pos.x + npc.velocity.x * cell * dt;
        let new_z = bevy_pos.z + npc.velocity.z * cell * dt;

        // Cached ground lookup: O(1) after first query per cell.
        // The cache stores absolute leaf Y internally, so the anchor
        // only affects the bevy-space XZ used for the cache key. We
        // pass player-anchor coords for key stability across frames.
        let player_bevy = bevy_from_position(&npc.position, &anchor);
        let ground_y_player_frame = ground_cache.ground_y(
            &world, &anchor, zoom.layer,
            player_bevy.x + npc.velocity.x * cell * dt,
            player_bevy.z + npc.velocity.z * cell * dt,
            cell,
        );

        // Convert from player-anchor frame to NPC-local frame.
        let ground_y = if ground_y_player_frame.is_nan() {
            // Cache budget exhausted -- keep current height.
            bevy_pos.y
        } else {
            // ground_y in player frame = (absolute_leaf_y - player_anchor_y).
            // We need it in NPC frame  = (absolute_leaf_y - npc_anchor_y).
            // Difference: (npc_anchor_y - player_anchor_y) added to the
            // player-frame value... but since both are just
            // (absolute - anchor), we can compute directly:
            // ground_y_npc = ground_y_player + (player_anchor_y - npc_anchor_y)
            let anchor_dy = (anchor.leaf_coord[1] - npc_anchor.leaf_coord[1]) as f32;
            ground_y_player_frame + anchor_dy
        };

        // Apply gravity only when above ground.
        let new_y = if bevy_pos.y > ground_y + 0.01 {
            npc.velocity.y -= NPC_GRAVITY_CELLS * cell * dt;
            bevy_pos.y + npc.velocity.y * dt
        } else {
            npc.velocity.y = 0.0;
            ground_y
        };

        let final_y = new_y.max(ground_y);

        let new_bevy = Vec3::new(new_x, final_y, new_z);
        if let Some(new_pos) = position_from_bevy(new_bevy, &npc_anchor) {
            npc.position = new_pos;
        }
    }
}

// ====================================================== zoom despawn

/// Clear NPC buffer when zoomed 2+ layers out from leaf layer.
fn npc_despawn_on_zoom(
    zoom: Res<CameraZoom>,
    mut npc_buffer: ResMut<NpcBuffer>,
) {
    if !zoom.is_changed() {
        return;
    }
    let layers_out = crate::world::tree::MAX_LAYER.saturating_sub(zoom.layer);
    if layers_out >= 2 {
        npc_buffer.npcs.clear();
    }
}

// ============================================== overlay collection (buffer-based)

/// Populate `OverlayList` from the flat NPC buffer.
pub fn collect_overlays_from_buffer(
    blueprints: Option<Res<TreeBlueprints>>,
    zoom: Res<CameraZoom>,
    anchor: Res<WorldAnchor>,
    camera_q: Query<(&Transform, &FpsCam), With<Camera3d>>,
    npc_buffer: Res<NpcBuffer>,
    npc_overrides: Query<(&NpcHandle, &NpcPartOverrides)>,
    mut overlay_list: ResMut<OverlayList>,
) {
    overlay_list.clear_and_recycle();

    let Some(blueprints) = blueprints else { return };
    if blueprints.blueprints.is_empty() { return; }

    let layers_out = crate::world::tree::MAX_LAYER.saturating_sub(zoom.layer);
    if layers_out >= 2 {
        return;
    }

    let (cam_pos, cam_forward) = if let Ok((cam_tf, cam)) = camera_q.single() {
        let fwd = Vec3::new(-cam.yaw.sin(), 0.0, -cam.yaw.cos());
        (cam_tf.translation, fwd)
    } else {
        (Vec3::ZERO, Vec3::NEG_Z)
    };
    let cell = cell_size_at_layer(zoom.layer);
    let view_radius = crate::world::render::RADIUS_VIEW_CELLS * cell;
    let view_radius_sq = view_radius * view_radius;

    // Pre-compute scale per blueprint type.
    let scales: Vec<f32> = blueprints.blueprints.iter()
        .map(|bp| tree_npc_scale(crate::world::tree::MAX_LAYER, bp))
        .collect();

    let mut override_map: HashMap<usize, &NpcPartOverrides> = HashMap::new();
    for (handle, overrides) in &npc_overrides {
        if !overrides.overrides.is_empty() {
            override_map.insert(handle.0, overrides);
        }
    }

    for (idx, npc) in npc_buffer.npcs.iter().enumerate() {
        if !npc.alive { continue; }

        let bp_idx = npc.blueprint_idx as usize % blueprints.blueprints.len();
        let bp = &blueprints.blueprints[bp_idx];
        let scale = scales[bp_idx];

        let bevy_pos = bevy_from_position(&npc.position, &anchor);

        let to_npc = bevy_pos - cam_pos;
        if to_npc.length_squared() > view_radius_sq {
            continue;
        }
        let forward_dot = to_npc.x * cam_forward.x + to_npc.z * cam_forward.z;
        if forward_dot < -view_radius * 0.3 {
            continue;
        }

        let overrides = override_map.get(&idx);

        let mut parts = overlay_list.pop_spare_parts();
        parts.clear();
        for (i, tp) in bp.parts.iter().enumerate().take(npc.num_parts as usize) {
            let (offset, rotation) = npc.part_transforms[i];
            let node_id = overrides
                .and_then(|o| o.overrides.get(&i).copied())
                .unwrap_or(tp.node_id);
            parts.push(OverlayPart {
                node_id,
                offset,
                rotation,
                pivot: tp.pivot,
            });
        }

        // Use the handle entity if available (for editing), otherwise placeholder.
        let overlay_entity = npc.handle_entity.unwrap_or(Entity::PLACEHOLDER);

        overlay_list.entries.push(OverlayInstance {
            id: overlay_entity,
            parts,
            bevy_pos,
            rotation: npc.rotation,
            scale,
        });
    }
}

// ============================================== GPU sync

/// Sync NPC buffer state to GPU data each frame.
fn sync_gpu_uniforms(
    time: Res<Time>,
    npc_buffer: Res<NpcBuffer>,
    mut gpu_data: ResMut<NpcGpuData>,
) {
    gpu_data.uniforms.delta_time = time.delta_secs();
    gpu_data.uniforms.frame = gpu_data.uniforms.frame.wrapping_add(1);
    gpu_data.uniforms.npc_count = npc_buffer.npcs.len() as u32;
}

// ============================================== NPC handle entities for editing

/// Maximum distance from player for NPC editing (bevy units).
const EDIT_RANGE: f32 = 20.0;

/// System that creates/destroys lightweight ECS handle entities
/// for NPCs near the player, enabling per-NPC voxel editing.
fn manage_npc_handles(
    mut commands: Commands,
    mut npc_buffer: ResMut<NpcBuffer>,
    anchor: Res<WorldAnchor>,
    player_q: Query<&Transform, With<Player>>,
    existing_handles: Query<(Entity, &NpcHandle)>,
) {
    let Ok(player_tf) = player_q.single() else { return };
    let player_pos = player_tf.translation;

    // Despawn handles for NPCs that moved out of range or died.
    for (entity, handle) in &existing_handles {
        let idx = handle.0;
        let in_range = npc_buffer.npcs.get(idx).is_some_and(|npc| {
            if !npc.alive { return false; }
            let bp = bevy_from_position(&npc.position, &anchor);
            bp.distance_squared(player_pos) <= EDIT_RANGE * EDIT_RANGE * 4.0
        });
        if !in_range {
            commands.entity(entity).despawn();
            if let Some(npc) = npc_buffer.npcs.get_mut(idx) {
                npc.handle_entity = None;
            }
        }
    }

    // Create handles for nearby NPCs that don't have one.
    for (idx, npc) in npc_buffer.npcs.iter_mut().enumerate() {
        if !npc.alive || npc.handle_entity.is_some() { continue; }

        let bevy_pos = bevy_from_position(&npc.position, &anchor);
        if bevy_pos.distance_squared(player_pos) > EDIT_RANGE * EDIT_RANGE {
            continue;
        }

        let entity = commands.spawn((
            Npc,
            NpcHandle(idx),
            NpcPartOverrides::default(),
        )).id();
        npc.handle_entity = Some(entity);
    }
}

// ============================================== JS spawn bridge (WASM only)

/// Check `window.__spawnNpcs` from JS each frame.
#[cfg(target_arch = "wasm32")]
fn js_spawn_bridge(
    tree_bp: Option<Res<TreeBlueprint>>,
    player_q: Query<&WorldPosition, With<Player>>,
    mut npc_buffer: ResMut<NpcBuffer>,
    mut gpu_data: ResMut<NpcGpuData>,
    anchor: Res<WorldAnchor>,
    zoom: Res<CameraZoom>,
    cam_q: Query<&FpsCam>,
) {
    // Call the __getAndResetSpawnCount function defined in index.html <head>.
    let result = js_sys::eval("window.__getAndResetSpawnCount()");
    let count = result
        .ok()
        .and_then(|v| v.as_f64())
        .unwrap_or(0.0) as usize;
    if count == 0 { return; }

    let Some(tree_bp) = tree_bp else { return };
    let Ok(player_pos) = player_q.single() else { return };

    let cell = cell_size_at_layer(zoom.layer);
    let forward = if let Ok(cam) = cam_q.single() {
        Vec3::new(-cam.yaw.sin(), 0.0, -cam.yaw.cos())
    } else {
        Vec3::NEG_Z
    };
    let player_bevy = bevy_from_position(&player_pos.0, &anchor);
    let num_parts = tree_bp.parts.len();
    let existing = npc_buffer.len();

    let mut rest_parts = [(Vec3::ZERO, Quat::IDENTITY); MAX_PARTS];
    for (i, p) in tree_bp.parts.iter().enumerate().take(MAX_PARTS) {
        rest_parts[i] = (p.rest_offset, Quat::IDENTITY);
    }

    npc_buffer.npcs.reserve(count);

    for i in 0..count {
        let (offset_x, offset_z) = if count > 1 {
            let grid_side = (count as f32).sqrt().ceil() as usize;
            let row = i / grid_side;
            let col = i % grid_side;
            let spacing = 3.0 * cell;
            let half = (grid_side as f32) * spacing / 2.0;
            (col as f32 * spacing - half, row as f32 * spacing - half)
        } else {
            (0.0, 0.0)
        };

        let npc_bevy = player_bevy
            + forward * 5.0 * cell
            + Vec3::new(offset_x, 1.0, offset_z);
        let Some(npc_pos) = position_from_bevy(npc_bevy, &anchor) else {
            continue;
        };

        let heading = rand_heading_seeded(i as u32);
        let mut npc = NpcState::new(npc_pos, heading, num_parts);
        npc.anim_time = rand_f32_seeded(i as u32 + 5555) * 2.0;
        npc.ai_timer = 2.0 + rand_f32_seeded(i as u32 + 9999) * 3.0;
        npc.part_transforms = rest_parts;

        let bevy_pos = bevy_from_position(&npc.position, &anchor);
        gpu_data.states.push(GpuNpcState {
            position: bevy_pos.to_array(),
            heading: npc.heading,
            velocity: [0.0; 3],
            ai_timer: npc.ai_timer,
            anim_time: npc.anim_time,
            speed: NPC_WALK_SPEED_CELLS * cell,
            seed: i as u32 + 42,
            flags: 1,
        });

        npc_buffer.npcs.push(npc);
    }

    gpu_data.dirty = true;
    info!("JS bridge: spawned {} NPCs (buffer len now {})", count, npc_buffer.npcs.len());
}

#[cfg(not(target_arch = "wasm32"))]
fn js_spawn_bridge() {}

// ============================================== NPC voxel editing

/// Edit a single voxel on an NPC part. Clone-on-write: clones the
/// leaf voxel grid, patches one cell, inserts the new leaf, and
/// stores the new NodeId in the per-instance overrides.
pub fn edit_npc_voxel(
    world: &mut WorldState,
    overrides: &mut NpcPartOverrides,
    tree_bp: &TreeBlueprint,
    part_index: usize,
    local_voxel: [u8; 3],
    new_voxel: Voxel,
) {
    let base_id = overrides
        .overrides
        .get(&part_index)
        .copied()
        .unwrap_or(tree_bp.parts[part_index].node_id);

    let mut new_voxels = world
        .library
        .get(base_id)
        .expect("edit_npc_voxel: part node missing")
        .voxels
        .clone();
    new_voxels[voxel_idx(
        local_voxel[0] as usize,
        local_voxel[1] as usize,
        local_voxel[2] as usize,
    )] = new_voxel;
    let new_id = world.library.insert_leaf(new_voxels);
    overrides.overrides.insert(part_index, new_id);
}

// ============================================================= helpers

fn tree_npc_scale(view_layer: u8, tree_bp: &TreeBlueprint) -> f32 {
    let max_y: f32 = tree_bp
        .parts
        .iter()
        .map(|p| p.rest_offset.y + p.size[1] as f32)
        .fold(0.0f32, f32::max);
    let height = max_y.max(1.0);
    let cell = cell_size_at_layer(view_layer);
    (1.5 * cell) / height
}

fn rand_f32() -> f32 {
    #[cfg(not(target_arch = "wasm32"))]
    {
        let t = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .subsec_nanos();
        (t % 10000) as f32 / 10000.0
    }
    #[cfg(target_arch = "wasm32")]
    {
        let t = (js_sys::Date::now() * 1000.0) as u64;
        ((t % 10000) as f32) / 10000.0
    }
}

/// Deterministic pseudo-random f32 in [0, 1) from a seed.
fn rand_f32_seeded(seed: u32) -> f32 {
    let mut s = seed.wrapping_mul(747796405).wrapping_add(2891336453);
    s = ((s >> 16) ^ s).wrapping_mul(0x45d9f3b);
    s = ((s >> 16) ^ s).wrapping_mul(0x45d9f3b);
    s = (s >> 16) ^ s;
    (s % 10000) as f32 / 10000.0
}

fn rand_heading_seeded(seed: u32) -> f32 {
    rand_f32_seeded(seed) * TAU
}
